Repository facebookresearch/nevergrad, pull requests merged in 2019-06, with the labels that each got.

#234 Make benchmark workflow more robust
  nevergrad/benchmark/test_xpbase.py
  nevergrad/benchmark/xpbase.py
Labels: CLA Signed

#233 Prepare for documentation generation
  .github/CONTRIBUTING.md
  .gitignore
  docs/Makefile
  docs/conf.py
  docs/index.rst
  docs/instrumentation_api.rst
  docs/make.bat
  docs/optimizers.rst
  nevergrad/__init__.py
  nevergrad/instrumentation/__init__.py
  nevergrad/instrumentation/core.py
  nevergrad/instrumentation/instantiate.py
  nevergrad/instrumentation/variables.py
  nevergrad/optimization/base.py
  nevergrad/optimization/differentialevolution.py
  nevergrad/optimization/families.py
  nevergrad/optimization/optimizerlib.py
  nevergrad/optimization/requirements_check.py
  requirements/dev.txt
Labels: Difficulty: Low, Priority: Low, Type: Enhancement

#235 Use octave-cli and deactivate flake checks
  nevergrad/functions/photonics/core.py
  nevergrad/optimization/optimizerlib.py
Labels: CLA Signed

#230 Add Registry Import to Readme.md
  README.md
Labels: CLA Signed

#236 Update precommit hooks
  .pre-commit-config.yaml
  nevergrad/benchmark/experiments.py
Labels: CLA Signed

#237 modification so that fight_all comes back
  nevergrad/benchmark/plotting.py
  nevergrad/benchmark/test_plotting.py
  nevergrad/common/test_tools.py
  nevergrad/common/tools.py
Labels: CLA Signed

#238 Experiment on formatting with black
  nevergrad/benchmark/core.py
  nevergrad/benchmark/plotting.py
  nevergrad/common/tools.py
  nevergrad/optimization/base.py
  nevergrad/optimization/optimizerlib.py
Labels: CLA Signed

#240 Download MLDA dataset even without verification
  nevergrad/functions/mlda/datasets.py
Labels: CLA Signed

#242 Add 007 game testbed
  CHANGELOG.md
  nevergrad/benchmark/experiments.py
  nevergrad/benchmark/test_experiments.py
  nevergrad/benchmark/xpbase.py
  nevergrad/functions/rl/__init__.py
  nevergrad/functions/rl/agents.py
  nevergrad/functions/rl/base.py
  nevergrad/functions/rl/envs.py
  nevergrad/functions/rl/test_agents.py
  nevergrad/functions/rl/test_envs.py
  requirements/bench.txt
Labels: CLA Signed

#241 Move the random state to the instrumentation
  CHANGELOG.md
  docs/adding_an_algorithm.md
  docs/instrumentation.md
  docs/optimization.md
  nevergrad/benchmark/test_xpbase.py
  nevergrad/benchmark/xpbase.py
  nevergrad/functions/arcoating/core.py
  nevergrad/instrumentation/core.py
  nevergrad/instrumentation/discretization.py
  nevergrad/instrumentation/test_core.py
  nevergrad/instrumentation/test_discretization.py
  nevergrad/instrumentation/test_variables.py
  nevergrad/instrumentation/utils.py
  nevergrad/instrumentation/variables.py
  nevergrad/optimization/base.py
  nevergrad/optimization/differentialevolution.py
  nevergrad/optimization/oneshot.py
  nevergrad/optimization/optimizerlib.py
  nevergrad/optimization/recastlib.py
  nevergrad/optimization/recorded_recommendations.csv
  nevergrad/optimization/test_optimizerlib.py
Labels: CLA Signed, Difficulty: Medium, Priority: Critical

#244 Fix typo in CONTRIBUTING.md
  .github/CONTRIBUTING.md
Labels: CLA Signed

#246 Minor core functions optimization
  nevergrad/functions/corefuncs.py
  nevergrad/functions/test_corefuncs.py
Labels: CLA Signed

#247 Add a couple of corefuncs
  nevergrad/benchmark/xpbase.py
  nevergrad/common/decorators.py
  nevergrad/functions/corefuncs.py
  nevergrad/functions/test_corefuncs.py
Labels: CLA Signed

#248 Rltyping
  nevergrad/functions/rl/agents.py
Labels: CLA Signed

#249 Prepare for version 0.2.2
  CHANGELOG.md
  docs/conf.py
  docs/make.bat
  nevergrad/functions/rl/__init__.py
  nevergrad/functions/rl/agents.py
  nevergrad/functions/rl/base.py
  nevergrad/functions/rl/envs.py
  nevergrad/functions/rl/test_agents.py
  nevergrad/functions/rl/test_envs.py
Labels: CLA Signed

#250 Update version to 0.2.2
  nevergrad/__init__.py
Labels: CLA Signed
