Repository facebookresearch/nevergrad, pull requests merged in 2019-05, with the labels that each got.

#188 Update ML example
  docs/machinelearning.md
  nevergrad/instrumentation/variables.py
Labels: CLA Signed

#191 Update dependency test
  .circleci/config.yml
  nevergrad/common/testing.py
  nevergrad/optimization/requirements_check.py
Labels: CLA Signed

#194 Rename asfloat to asscalar and allow int casting
  CHANGELOG.md
  docs/instrumentation.md
  docs/machinelearning.md
  docs/optimization.md
  nevergrad/benchmark/additional/example.py
  nevergrad/functions/mlda/problems.py
  nevergrad/instrumentation/core.py
  nevergrad/instrumentation/test_variables.py
  nevergrad/instrumentation/variables.py
  nevergrad/optimization/optimizerlib.py
  nevergrad/optimization/requirements_check.py
  nevergrad/optimization/test_optimizerlib.py
Labels: CLA Signed

#196 addingdoc
  nevergrad/functions/corefuncs.py
Labels: CLA Signed

#197 Fixed tell not asked for the DE family
  nevergrad/optimization/differentialevolution.py
Labels: CLA Signed

#199 Added dump and load methods for optimizers
  nevergrad/optimization/base.py
  nevergrad/optimization/differentialevolution.py
  nevergrad/optimization/optimizerlib.py
  nevergrad/optimization/test_base.py
  nevergrad/optimization/test_optimizerlib.py
Labels: CLA Signed

#186 Fix optimizer when having started more jobs than workers
  nevergrad/optimization/base.py
Labels: CLA Signed

#200 Allow more parameters for BO
  nevergrad/optimization/optimizerlib.py
Labels: CLA Signed

#201 Add a header
  nevergrad/optimization/requirements_check.py
Labels: CLA Signed

#202 Add bound checks for backward transforms
  nevergrad/instrumentation/test_transforms.py
  nevergrad/instrumentation/transforms.py
  nevergrad/optimization/test_optimizerlib.py
Labels: CLA Signed

#203 Use arctan in BO and bounded array
  CHANGELOG.md
  nevergrad/instrumentation/variables.py
  nevergrad/optimization/optimizerlib.py
  nevergrad/optimization/recorded_recommendations.csv
  nevergrad/optimization/test_optimizerlib.py
Labels: CLA Signed

#204 Prevent bayesian optimization in discontinuous/noisy cases
  CHANGELOG.md
  nevergrad/instrumentation/core.py
  nevergrad/instrumentation/test_core.py
  nevergrad/instrumentation/test_utils.py
  nevergrad/instrumentation/utils.py
  nevergrad/instrumentation/variables.py
  nevergrad/optimization/optimizerlib.py
  nevergrad/optimization/test_optimizerlib.py
Labels: CLA Signed

#205 Add clipping for bounds
  nevergrad/instrumentation/test_transforms.py
  nevergrad/instrumentation/transforms.py
  nevergrad/instrumentation/variables.py
Labels: CLA Signed

#207 Correct BO GP parameters error
  nevergrad/optimization/optimizerlib.py
  nevergrad/optimization/test_optimizerlib.py
Labels: CLA Signed

#208 Update XP result plot legends
  CHANGELOG.md
  docs/resources/compabasedillcond_r400s12_xpresults_nameellipsoid,rotationTrue.png
  docs/resources/dim10_select_one_feature_r400s12_xpresults.png
  docs/resources/dim10_select_two_features_r400s12_xpresults.png
  docs/resources/dim10_smallbudget_r400s12_xpresults.png
  docs/resources/doe_dim4_r400s12_xpresults.png
  docs/resources/illcond_r50s12_xpresults_namecigar,rotationTrue.png
  docs/resources/noise_r400s12_xpresults_namecigar,rotationTrue.png
  docs/resources/small_discrete_r10s12_xpresults_dimension330,namehardleadingones5,useless_variables300.png
  docs/resources/small_discrete_r10s12_xpresults_dimension330,namehardonemax5,useless_variables300.png
  nevergrad/benchmark/plotting.py
  nevergrad/benchmark/test_plotting.py
Labels: CLA Signed

#206 Add inefficiency warnings
  CHANGELOG.md
  nevergrad/benchmark/test_core.py
  nevergrad/optimization/differentialevolution.py
  nevergrad/optimization/optimizerlib.py
  nevergrad/optimization/test_optimizerlib.py
Labels: CLA Signed

#209 Update for release 0.2.1
  CHANGELOG.md
  nevergrad/__init__.py
  setup.py
Labels: CLA Signed

#210 Deactivate log for negative values
  nevergrad/benchmark/plotting.py
  nevergrad/common/tools.py
Labels: CLA Signed

#212 Update CEC2019.md
  docs/CEC2019.md
Labels: CLA Signed

#213 Add representations for population and particles
  nevergrad/optimization/differentialevolution.py
  nevergrad/optimization/optimizerlib.py
  nevergrad/optimization/test_utils.py
  nevergrad/optimization/utils.py
Labels: CLA Signed

#215 Add check for Affine transform
  nevergrad/instrumentation/transforms.py
Labels: CLA Signed

#217 Add a random generator to all optimizers
  CHANGELOG.md
  docs/adding_an_algorithm.md
  docs/optimization.md
  nevergrad/benchmark/test_xpbase.py
  nevergrad/optimization/base.py
  nevergrad/optimization/differentialevolution.py
  nevergrad/optimization/mutations.py
  nevergrad/optimization/oneshot.py
  nevergrad/optimization/optimizerlib.py
  nevergrad/optimization/recorded_recommendations.csv
  nevergrad/optimization/sequences.py
  nevergrad/optimization/test_mutations.py
  nevergrad/optimization/test_optimizerlib.py
  nevergrad/optimization/test_sequences.py
Labels: CLA Signed, Difficulty: High, Priority: Medium, Status: Feedbacks welcomed, Status: In Progess, Type: Enhancement

#220 Deactivate CMA log
  nevergrad/optimization/optimizerlib.py
Labels: CLA Signed

#216 Add a Scalar variable
  CHANGELOG.md
  docs/instrumentation.md
  nevergrad/instrumentation/core.py
  nevergrad/instrumentation/test_variables.py
  nevergrad/instrumentation/variables.py
Labels: CLA Signed, Priority: Medium, Status: Review needed, Type: Enhancement

#219 Add a mechanism to suggest a given candidate
  CHANGELOG.md
  nevergrad/optimization/base.py
  nevergrad/optimization/test_base.py
  nevergrad/optimization/test_optimizerlib.py
Labels: CLA Signed, Priority: High, Status: Review needed, Type: Enhancement

#214 Improve nevergrad namespace
  CHANGELOG.md
  README.md
  docs/adding_an_algorithm.md
  docs/instrumentation.md
  docs/machinelearning.md
  docs/optimization.md
  nevergrad/__init__.py
  nevergrad/benchmark/additional/example.py
  nevergrad/optimization/requirements_check.py
Labels: CLA Signed, Priority: Medium, Status: Review needed, Type: Enhancement

#218 Rename optimize method to minimize
  CHANGELOG.md
  docs/instrumentation.md
  docs/machinelearning.md
  docs/optimization.md
  nevergrad/benchmark/test_xpbase.py
  nevergrad/benchmark/xpbase.py
  nevergrad/optimization/base.py
  nevergrad/optimization/requirements_check.py
  nevergrad/optimization/test_base.py
  nevergrad/optimization/test_optimizerlib.py
  nevergrad/optimization/test_recaster.py
Labels: Priority: Low, Status: Feedbacks welcomed, Type: Breaking changes, Type: Enhancement

#223 Try to make population grow
  nevergrad/optimization/differentialevolution.py
  nevergrad/optimization/test_optimizerlib.py
Labels: CLA Signed

#221 Begin simplifying`DifferentialEvolution` structure
  nevergrad/optimization/differentialevolution.py
  nevergrad/optimization/recorded_recommendations.csv
  nevergrad/optimization/test_mutations.py
  nevergrad/optimization/test_optimizerlib.py
Labels: CLA Signed, Difficulty: High, Priority: High, Status: In Progess, Type: Refactoring

#225 Improve def and readability of crossovers
  nevergrad/optimization/differentialevolution.py
  nevergrad/optimization/recorded_recommendations.csv
  nevergrad/optimization/test_mutations.py
Labels: CLA Signed

#226 Merge particule/individual classes
  nevergrad/optimization/differentialevolution.py
  nevergrad/optimization/optimizerlib.py
  nevergrad/optimization/test_utils.py
  nevergrad/optimization/utils.py
Labels: CLA Signed

#228 Remove unused population link
  nevergrad/optimization/test_utils.py
  nevergrad/optimization/utils.py
Labels: CLA Signed

#229 Add a split data function on instrumentation
  nevergrad/instrumentation/core.py
  nevergrad/instrumentation/test_core.py
  nevergrad/instrumentation/utils.py
Labels: CLA Signed
