Repository facebookresearch/nevergrad, pull requests merged in 2020-01, with the labels that each got.

#424 new chain CMA + Powell
  nevergrad/optimization/optimizerlib.py
  nevergrad/optimization/recorded_recommendations.csv
Labels: CLA Signed

#425 Update experiments.py
  nevergrad/benchmark/experiments.py
Labels: CLA Signed

#427 minorfix
  nevergrad/benchmark/plotting.py
Labels: CLA Signed

#426 NGO: in low dim and hard thresholding, use FastGA variant
  nevergrad/optimization/optimizerlib.py
Labels: CLA Signed

#428 one more alg in yabbob
  nevergrad/benchmark/experiments.py
Labels: CLA Signed

#418 Update experiments.py: more diversity in realworld
  nevergrad/benchmark/experiments.py
Labels: CLA Signed

#429 Link to the Fb group
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
Labels: CLA Signed

#421 Replace InstrumentedFunction by ExperimentFunction (different API)
  CHANGELOG.md
  docs/benchmarking.md
  docs/instrumentation.md
  nevergrad/benchmark/additional/example.py
  nevergrad/benchmark/execution.py
  nevergrad/benchmark/experiments.py
  nevergrad/benchmark/frozenexperiments.py
  nevergrad/benchmark/test_core.py
  nevergrad/benchmark/test_execution.py
  nevergrad/benchmark/test_experiments.py
  nevergrad/benchmark/test_xpbase.py
  nevergrad/benchmark/xpbase.py
  nevergrad/functions/__init__.py
  nevergrad/functions/arcoating/core.py
  nevergrad/functions/arcoating/test_core.py
  nevergrad/functions/base.py
  nevergrad/functions/corefuncs.py
  nevergrad/functions/functionlib.py
  nevergrad/functions/games/game.py
  nevergrad/functions/games/test_game.py
  nevergrad/functions/mlda/problems.py
  nevergrad/functions/mlda/test_problems.py
  nevergrad/functions/photonics/core.py
  nevergrad/functions/photonics/test_core.py
  nevergrad/functions/powersystems/__init__.py
  nevergrad/functions/powersystems/core.py
  nevergrad/functions/powersystems/test_core.py
  nevergrad/functions/rl/agents.py
  nevergrad/functions/rl/base.py
  nevergrad/functions/rl/test_agents.py
  nevergrad/functions/stsp/__init__.py
  nevergrad/functions/stsp/core.py
  nevergrad/functions/test_base.py
  nevergrad/functions/test_functionlib.py
  nevergrad/functions/utils.py
  nevergrad/instrumentation/core.py
  nevergrad/instrumentation/multivariables.py
  nevergrad/instrumentation/test_multivariables.py
  nevergrad/instrumentation/variables.py
Labels: CLA Signed, Difficulty: Medium, Priority: Critical, Type: Breaking changes, Type: Bug

#432 Merge master with ExperimentFunction
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.md
  README.md
  docs/benchmarking.md
  docs/instrumentation.md
  nevergrad/benchmark/additional/example.py
  nevergrad/benchmark/execution.py
  nevergrad/benchmark/experiments.py
  nevergrad/benchmark/frozenexperiments.py
  nevergrad/benchmark/plotting.py
  nevergrad/benchmark/test_core.py
  nevergrad/benchmark/test_execution.py
  nevergrad/benchmark/test_experiments.py
  nevergrad/benchmark/test_xpbase.py
  nevergrad/benchmark/xpbase.py
  nevergrad/functions/__init__.py
  nevergrad/functions/arcoating/core.py
  nevergrad/functions/arcoating/test_core.py
  nevergrad/functions/base.py
  nevergrad/functions/corefuncs.py
  nevergrad/functions/functionlib.py
  nevergrad/functions/games/game.py
  nevergrad/functions/games/test_game.py
  nevergrad/functions/mlda/problems.py
  nevergrad/functions/mlda/test_problems.py
  nevergrad/functions/photonics/core.py
  nevergrad/functions/photonics/test_core.py
  nevergrad/functions/powersystems/__init__.py
  nevergrad/functions/powersystems/core.py
  nevergrad/functions/powersystems/test_core.py
  nevergrad/functions/rl/agents.py
  nevergrad/functions/rl/base.py
  nevergrad/functions/rl/test_agents.py
  nevergrad/functions/stsp/__init__.py
  nevergrad/functions/stsp/core.py
  nevergrad/functions/test_base.py
  nevergrad/functions/test_functionlib.py
  nevergrad/functions/utils.py
  nevergrad/instrumentation/multivariables.py
  nevergrad/instrumentation/test_multivariables.py
  nevergrad/optimization/optimizerlib.py
  nevergrad/optimization/recorded_recommendations.csv
Labels: CLA Signed

#434 Change typing import in parametrization for consistency
  nevergrad/benchmark/experiments.py
  nevergrad/parametrization/choice.py
  nevergrad/parametrization/container.py
  nevergrad/parametrization/core.py
  nevergrad/parametrization/data.py
  nevergrad/parametrization/test_parameter.py
Labels: CLA Signed

#436 Satisfy endogeneous constaints
  nevergrad/parametrization/core.py
  nevergrad/parametrization/test_parameter.py
Labels: CLA Signed

#437 Add meta and heritage system for Parameter
  nevergrad/parametrization/core.py
  nevergrad/parametrization/data.py
  nevergrad/parametrization/test_parameter.py
Labels: CLA Signed

#435 update xps
  nevergrad/benchmark/experiments.py
Labels: CLA Signed

#441 Getting rid of candidate maker
  nevergrad/optimization/base.py
  nevergrad/optimization/differentialevolution.py
  nevergrad/optimization/optimizerlib.py
  nevergrad/optimization/test_base.py
  nevergrad/optimization/test_optimizerlib.py
  nevergrad/parametrization/data.py
Labels: CLA Signed

#442 Prepare for v0.3.0 release
  CHANGELOG.md
Labels: CLA Signed

#438 Update opencompetition2020.md
  docs/opencompetition2020.md
Labels: CLA Signed

#450 Install numpy stubs automatically + update doc
  .circleci/config.yml
  .github/CONTRIBUTING.md
  requirements/dev.txt
  setup.py
Labels: CLA Signed

#452 Update headers
  nevergrad/functions/games/test_game.py
  nevergrad/parametrization/core.py
Labels: CLA Signed

#446 Replace Octave Photonics code by python code
  .circleci/config.yml
  nevergrad/benchmark/test_experiments.py
  nevergrad/functions/photonics/__init__.py
  nevergrad/functions/photonics/core.py
  nevergrad/functions/photonics/photonics.py
  nevergrad/functions/photonics/src/CREDIT
  nevergrad/functions/photonics/src/bragg.m
  nevergrad/functions/photonics/src/c_bas.m
  nevergrad/functions/photonics/src/cascade.m
  nevergrad/functions/photonics/src/chirped.m
  nevergrad/functions/photonics/src/creneau.m
  nevergrad/functions/photonics/src/homogene.m
  nevergrad/functions/photonics/src/interface.m
  nevergrad/functions/photonics/src/marche.m
  nevergrad/functions/photonics/src/morpho.m
  nevergrad/functions/photonics/test_core.py
  setup.py
Labels: CLA Signed

#456 Rename Dict._parameters to Dict._content
  nevergrad/parametrization/choice.py
  nevergrad/parametrization/container.py
  nevergrad/parametrization/core.py
  nevergrad/parametrization/data.py
Labels: CLA Signed

#457 Rename Parameter.subparameters to Parameter.parameters
  nevergrad/parametrization/core.py
  nevergrad/parametrization/data.py
Labels: CLA Signed

#454 Remove CMA as one shot
  nevergrad/optimization/optimizerlib.py
Labels: CLA Signed

#458 Update opencompetition2020.md
  docs/opencompetition2020.md
Labels: CLA Signed

#460 add doc
  nevergrad/benchmark/experiments.py
Labels: CLA Signed

#461 Center and reduce standardized_space relatively to reference
  nevergrad/instrumentation/core.py
  nevergrad/parametrization/choice.py
  nevergrad/parametrization/container.py
  nevergrad/parametrization/core.py
  nevergrad/parametrization/data.py
  nevergrad/parametrization/test_parameter.py
Labels: CLA Signed

#462 Use candidate uid instead of data as optimizer key
  nevergrad/optimization/optimizerlib.py
  nevergrad/optimization/recaster.py
  nevergrad/optimization/test_optimizerlib.py
Labels: CLA Signed

#464 Add the S in satisfies_constraintS
  nevergrad/parametrization/container.py
  nevergrad/parametrization/core.py
  nevergrad/parametrization/test_parameter.py
Labels: CLA Signed

#465 Move instantiation into parametrization
  CHANGELOG.md
  nevergrad/benchmark/core.py
  nevergrad/benchmark/test_core.py
  nevergrad/instrumentation/__init__.py
  nevergrad/instrumentation/utils.py
  nevergrad/optimization/optimizerlib.py
  nevergrad/optimization/requirements_check.py
  nevergrad/parametrization/__init__.py
  nevergrad/parametrization/examples/script.py
  nevergrad/parametrization/instantiate.py
  nevergrad/parametrization/test_instantiate.py
  nevergrad/parametrization/test_utils.py
  nevergrad/parametrization/utils.py
Labels: CLA Signed

#439 Add an OrderedSet tool
  nevergrad/common/test_tools.py
  nevergrad/common/tools.py
Labels: CLA Signed

#451 Make the development process (a bit more) Windows-friendly
  docs/benchmarking.md
  docs/instrumentation.md
  nevergrad/benchmark/test_core.py
  nevergrad/common/test_testing.py
  nevergrad/common/test_tools.py
  nevergrad/common/testing.py
  nevergrad/parametrization/test_instantiate.py
Labels: CLA Signed

#468 Force use of reference to get standardized data
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  nevergrad/parametrization/core.py
  nevergrad/parametrization/test_parameter.py
Labels: CLA Signed

#455 Add reference for PSO
  nevergrad/optimization/optimizerlib.py
Labels: CLA Signed

#469 Update Log API
  nevergrad/parametrization/data.py
  nevergrad/parametrization/test_parameter.py
Labels: CLA Signed

#470 Empty recombine
  nevergrad/parametrization/core.py
  nevergrad/parametrization/data.py
  nevergrad/parametrization/test_parameter.py
Labels: CLA Signed

#467 Use standard initialization for PSO instead of full real space sampling
  CHANGELOG.md
  nevergrad/optimization/optimizerlib.py
  nevergrad/optimization/recorded_recommendations.csv
  nevergrad/optimization/test_optimizerlib.py
Labels: CLA Signed, Difficulty: Low, Priority: Low, Status: On hold, Type: Bug

#473 Prepare for release 0.3.1
  CHANGELOG.md
  nevergrad/__init__.py
Labels: CLA Signed

#474 minor docfix
  README.md
Labels: CLA Signed

#472 Add new optimizers
  nevergrad/benchmark/experiments.py
  nevergrad/optimization/optimizerlib.py
  nevergrad/optimization/recorded_recommendations.csv
Labels: CLA Signed

#475 Add repr to Descriptors
  nevergrad/common/tools.py
  nevergrad/optimization/base.py
  nevergrad/parametrization/test_utils.py
  nevergrad/parametrization/utils.py
Labels: CLA Signed

#479 Add time regression as informative data in tests
  nevergrad/optimization/test_optimizerlib.py
Labels: CLA Signed

#481 Correction of array sigmas
  nevergrad/benchmark/experiments.py
  nevergrad/parametrization/data.py
  nevergrad/parametrization/test_parameter.py
  nevergrad/parametrization/test_utils.py
  nevergrad/parametrization/transforms.py
Labels: CLA Signed

#483 Update DE to use Parameter
  nevergrad/optimization/base.py
  nevergrad/optimization/differentialevolution.py
  nevergrad/optimization/recorded_recommendations.csv
  nevergrad/optimization/test_optimizerlib.py
Labels: CLA Signed

#459 Replace Candidate by a Parameter
  CHANGELOG.md
  README.md
  docs/machinelearning.md
  docs/optimization.md
  docs/parametrization.md
  nevergrad/__init__.py
  nevergrad/benchmark/experiments.py
  nevergrad/benchmark/plotting.py
  nevergrad/benchmark/test_xpbase.py
  nevergrad/benchmark/xpbase.py
  nevergrad/functions/arcoating/test_core.py
  nevergrad/functions/base.py
  nevergrad/functions/functionlib.py
  nevergrad/functions/mlda/problems.py
  nevergrad/functions/mlda/test_problems.py
  nevergrad/functions/photonics/core.py
  nevergrad/functions/photonics/test_core.py
  nevergrad/functions/rl/agents.py
  nevergrad/functions/rl/test_agents.py
  nevergrad/functions/test_base.py
  nevergrad/instrumentation/multivariables.py
  nevergrad/instrumentation/variables.py
  nevergrad/optimization/base.py
  nevergrad/optimization/callbacks.py
  nevergrad/optimization/differentialevolution.py
  nevergrad/optimization/optimizerlib.py
  nevergrad/optimization/recaster.py
  nevergrad/optimization/recastlib.py
  nevergrad/optimization/requirements_check.py
  nevergrad/optimization/test_base.py
  nevergrad/optimization/test_callbacks.py
  nevergrad/optimization/test_optimizerlib.py
  nevergrad/optimization/test_recaster.py
  nevergrad/parametrization/container.py
  nevergrad/parametrization/core.py
  nevergrad/parametrization/test_parameter.py
Labels: CLA Signed, Difficulty: Medium, Priority: Critical, Status: Review needed

#471 Add a parameter-based ES algorithm and update DE to use parameters
  CHANGELOG.md
  nevergrad/benchmark/experiments.py
  nevergrad/functions/__init__.py
  nevergrad/functions/functionlib.py
  nevergrad/functions/test_functionlib.py
  nevergrad/optimization/base.py
  nevergrad/optimization/callbacks.py
  nevergrad/optimization/differentialevolution.py
  nevergrad/optimization/es.py
  nevergrad/optimization/families.py
  nevergrad/optimization/optimizerlib.py
  nevergrad/optimization/recorded_recommendations.csv
  nevergrad/optimization/test_callbacks.py
  nevergrad/optimization/test_optimizerlib.py
  nevergrad/optimization/test_utils.py
  nevergrad/optimization/utils.py
  nevergrad/parametrization/data.py
  nevergrad/parametrization/helpers.py
  nevergrad/parametrization/parameter.py
  nevergrad/parametrization/test_parameter.py
  nevergrad/parametrization/test_utils.py
  nevergrad/parametrization/transforms.py
  nevergrad/parametrization/utils.py
Labels: CLA Signed

#485 Fix issue with tell not asked of DE and PSO
  nevergrad/optimization/differentialevolution.py
  nevergrad/optimization/optimizerlib.py
  nevergrad/optimization/recorded_recommendations.csv
  nevergrad/optimization/test_optimizerlib.py
  nevergrad/optimization/test_utils.py
  nevergrad/optimization/utils.py
Labels: CLA Signed

#487 Integrate tooling for run visualization
  nevergrad/optimization/callbacks.py
  requirements/bench.txt
Labels: CLA Signed
