Repository facebookresearch/nevergrad, pull requests merged in 2020-02, with the labels that each got.

#488 Minor fixes to improve Windows compatibility
  .circleci/config.yml
  .github/CONTRIBUTING.md
  README.md
  nevergrad/benchmark/test_core.py
  nevergrad/benchmark/test_plotting.py
  nevergrad/common/tools.py
  nevergrad/functions/photonics/test_core.py
  nevergrad/optimization/requirements_check.py
  nevergrad/parametrization/test_instantiate.py
  nevergrad/parametrization/test_utils.py
  requirements/main.txt
Labels: CLA Signed

#491 Use a recombination_ratio instead of number
  nevergrad/benchmark/experiments.py
  nevergrad/optimization/es.py
Labels: CLA Signed

#493 Update CI
  .circleci/config.yml
Labels: CLA Signed

#496 Factorize CircleCI config
  .circleci/config.yml
Labels: CLA Signed

#477 Update photonics with better mutations and recombinations
  nevergrad/benchmark/experiments.py
  nevergrad/functions/photonics/core.py
  nevergrad/functions/photonics/test_core.py
Labels: CLA Signed

#497 Rename instrumentation to parametrization in optimizers init
  .circleci/config.yml
  CHANGELOG.md
  README.md
  docs/adding_an_algorithm.md
  docs/index.rst
  docs/instrumentation.md
  docs/instrumentation_api.rst
  docs/machinelearning.md
  docs/optimization.md
  docs/parametrization.md
  docs/parametrization_api.rst
  nevergrad/__init__.py
  nevergrad/benchmark/test_execution.py
  nevergrad/benchmark/xpbase.py
  nevergrad/functions/base.py
  nevergrad/functions/functionlib.py
  nevergrad/functions/mlda/test_problems.py
  nevergrad/functions/photonics/core.py
  nevergrad/functions/test_base.py
  nevergrad/functions/test_functionlib.py
  nevergrad/optimization/base.py
  nevergrad/optimization/callbacks.py
  nevergrad/optimization/differentialevolution.py
  nevergrad/optimization/es.py
  nevergrad/optimization/oneshot.py
  nevergrad/optimization/optimizerlib.py
  nevergrad/optimization/recaster.py
  nevergrad/optimization/recastlib.py
  nevergrad/optimization/test_base.py
  nevergrad/optimization/test_callbacks.py
  nevergrad/optimization/test_optimizerlib.py
  nevergrad/optimization/test_recaster.py
Labels: CLA Signed

#499 Get rid of deprecated code
  CHANGELOG.md
  docs/machinelearning.md
  docs/optimization.md
  docs/parametrization.md
  nevergrad/__init__.py
  nevergrad/benchmark/additional/example.py
  nevergrad/functions/multiobjective/test_core.py
  nevergrad/instrumentation/__init__.py
  nevergrad/instrumentation/core.py
  nevergrad/instrumentation/multivariables.py
  nevergrad/instrumentation/test_multivariables.py
  nevergrad/instrumentation/test_variables.py
  nevergrad/instrumentation/variables.py
  nevergrad/optimization/base.py
  nevergrad/optimization/differentialevolution.py
  nevergrad/optimization/optimizerlib.py
  nevergrad/optimization/recaster.py
  nevergrad/optimization/rescaledoneshot.py
  nevergrad/optimization/test_base.py
  nevergrad/optimization/test_utils.py
  nevergrad/parametrization/container.py
  nevergrad/parametrization/core.py
  nevergrad/parametrization/data.py
  nevergrad/parametrization/test_parameter.py
  nevergrad/parametrization/test_parameters_legacy.py
  nevergrad/parametrization/test_utils.py
Labels: CLA Signed

#501 Fix ES parallelization bug
  nevergrad/optimization/es.py
  nevergrad/optimization/test_optimizerlib.py
Labels: CLA Signed

#503 Avoid installing numpy stubs (not working well)
  .circleci/config.yml
  .github/CONTRIBUTING.md
  requirements/dev.txt
  setup.py
Labels: CLA Signed

#484 Maint: Hypervolume (pyhv.py) module rewrite
  README.md
  nevergrad/functions/multiobjective/LGPL_LICENSE
  nevergrad/functions/multiobjective/core.py
  nevergrad/functions/multiobjective/hypervolume.py
  nevergrad/functions/multiobjective/pyhv.py
  nevergrad/functions/multiobjective/test_structures.py
Labels: CLA Signed

#502 extracting a subset of the Pareto front
  docs/optimization.md
  nevergrad/functions/multiobjective/core.py
  nevergrad/functions/multiobjective/test_core.py
Labels: CLA Signed

#504 Minor fixes for the updated doc
  README.md
  docs/resources/TwoPointsDE.gif
  setup.py
Labels: CLA Signed

#494 [WIP] Add Windows CI
  .circleci/config.yml
Labels: CLA Signed

#505 fix flaky test
  nevergrad/functions/multiobjective/core.py
  nevergrad/functions/multiobjective/test_core.py
Labels: CLA Signed

#507 Skip flaky test on Windows
  docs/optimization.rst
  nevergrad/functions/multiobjective/test_core.py
  nevergrad/optimization/test_doc.py
  nevergrad/optimization/test_recaster.py
Labels: CLA Signed

#476 faster test
  .circleci/config.yml
  nevergrad/functions/games/test_game.py
Labels: CLA Signed

#509 Make the PSO recommendation test more relevant
  nevergrad/optimization/optimizerlib.py
  nevergrad/optimization/recorded_recommendations.csv
  nevergrad/optimization/test_optimizerlib.py
Labels: CLA Signed

#510 Update PSO to use new Parametrization system
  nevergrad/optimization/optimizerlib.py
  nevergrad/optimization/test_optimizerlib.py
  nevergrad/optimization/test_utils.py
  nevergrad/optimization/utils.py
Labels: CLA Signed

#511 Remove Individual from TBPSA
  nevergrad/optimization/optimizerlib.py
  nevergrad/optimization/utils.py
Labels: CLA Signed

#508 Add callback and doc
  docs/optimization.rst
  docs/optimizers_ref.rst
  nevergrad/__init__.py
  nevergrad/optimization/callbacks.py
  nevergrad/optimization/test_callbacks.py
  nevergrad/optimization/test_doc.py
Labels: CLA Signed

#514 Activate auto doc deployement
  .circleci/config.yml
Labels: CLA Signed

#512 Add a PSO version working directly in real space
  nevergrad/benchmark/experiments.py
  nevergrad/optimization/optimizerlib.py
  nevergrad/optimization/recorded_recommendations.csv
  nevergrad/optimization/test_optimizerlib.py
Labels: CLA Signed

#516 Propagate heritage in TBPSA and EDA
  nevergrad/optimization/callbacks.py
  nevergrad/optimization/optimizerlib.py
Labels: CLA Signed

#518 Simplify configurable optimizer API
  nevergrad/benchmark/xpbase.py
  nevergrad/common/tools.py
  nevergrad/optimization/base.py
  nevergrad/optimization/optimizerlib.py
  nevergrad/optimization/test_optimizerlib.py
  nevergrad/parametrization/utils.py
Labels: CLA Signed

#520 fix doc
  docs/benchmarks.rst
  docs/conf.py
  nevergrad/optimization/callbacks.py
Labels: CLA Signed

#519 mooplus
  nevergrad/functions/multiobjective/core.py
  nevergrad/functions/multiobjective/test_core.py
Labels: CLA Signed

#521 Propagate configured optimizer
  .circleci/config.yml
  CHANGELOG.md
  docs/optimizers_ref.rst
  nevergrad/benchmark/experiments.py
  nevergrad/benchmark/frozenexperiments.py
  nevergrad/benchmark/xpbase.py
  nevergrad/optimization/__init__.py
  nevergrad/optimization/base.py
  nevergrad/optimization/callbacks.py
  nevergrad/optimization/differentialevolution.py
  nevergrad/optimization/es.py
  nevergrad/optimization/oneshot.py
  nevergrad/optimization/optimizerlib.py
  nevergrad/optimization/recastlib.py
  nevergrad/optimization/rescaledoneshot.py
  nevergrad/optimization/test_base.py
  nevergrad/optimization/test_optimizerlib.py
Labels: CLA Signed

#523 Fix quasi opposite budget
  nevergrad/optimization/oneshot.py
  nevergrad/optimization/recorded_recommendations.csv
Labels: CLA Signed, Difficulty: Low, Priority: Medium, Type: Bug

#524 Update ConfiguredOptimizer doc
  nevergrad/optimization/base.py
Labels: CLA Signed

#526 Make PSO a configured optimizer
  nevergrad/optimization/optimizerlib.py
Labels: CLA Signed

#527 Link to more install options
  docs/getting_started.rst
  docs/index.rst
Labels: CLA Signed

#517 self contained example for ask and tell
  nevergrad/optimization/test_doc.py
Labels: CLA Signed

#522 shivatest
  docs/optimization.rst
  nevergrad/benchmark/experiments.py
  nevergrad/functions/corefuncs.py
  nevergrad/functions/test_corefuncs.py
  nevergrad/optimization/test_doc.py
Labels: CLA Signed

#534 Bug in photonics.chirped fixed.
  nevergrad/functions/photonics/photonics.py
Labels: CLA Signed

#531 Add an experimental torch optimization wrapper
  nevergrad/common/tools.py
  nevergrad/functions/rl/agents.py
  nevergrad/functions/rl/test_agents.py
  nevergrad/optimization/helpers.py
Labels: CLA Signed, Difficulty: Low, Priority: Low, Status: Review needed, Type: Enhancement

#532 docfix
  nevergrad/parametrization/data.py
Labels: CLA Signed

#539 Bug bragg + chirped fixed.
  nevergrad/functions/photonics/photonics.py
  nevergrad/functions/photonics/test_core.py
Labels: CLA Signed

#540 Improve photonics and ARCoating test beds
  nevergrad/functions/arcoating/core.py
  nevergrad/functions/arcoating/test_core.py
  nevergrad/functions/photonics/core.py
  nevergrad/functions/photonics/test_core.py
  nevergrad/parametrization/utils.py
Labels: CLA Signed

#535 fix doc about DE
  docs/contributing.rst
Labels: CLA Signed

#490 Update experiments.py
  nevergrad/benchmark/experiments.py
Labels: CLA Signed

#536 Rename a_min and a_max to lower and upper and add them to Scalar init
  CHANGELOG.md
  nevergrad/parametrization/data.py
  nevergrad/parametrization/test_parameter.py
  nevergrad/parametrization/test_parameters_legacy.py
Labels: CLA Signed

#528 Gather experimental variants together
  CHANGELOG.md
  nevergrad/benchmark/frozenexperiments.py
  nevergrad/optimization/differentialevolution.py
  nevergrad/optimization/experimentalvariants.py
  nevergrad/optimization/oneshot.py
  nevergrad/optimization/optimizerlib.py
  nevergrad/optimization/rescaledoneshot.py
  nevergrad/optimization/test_base.py
  nevergrad/optimization/test_optimizerlib.py
  nevergrad/optimization/test_utils.py
Labels: CLA Signed

#544 Update core.py
  nevergrad/functions/multiobjective/core.py
Labels: CLA Signed

#545 Create functions before looping + nits
  nevergrad/benchmark/experiments.py
Labels: CLA Signed

#549 Update core.py
  nevergrad/functions/multiobjective/core.py
Labels: CLA Signed

#543 MOO: autocomputation of the reference point
  nevergrad/functions/multiobjective/core.py
  nevergrad/functions/multiobjective/test_core.py
Labels: CLA Signed

#550 Deactivate Cobyla offset test on Windows
  nevergrad/optimization/test_optimizerlib.py
Labels: CLA Signed

#547 Simplify crossover
  nevergrad/functions/arcoating/core.py
  nevergrad/functions/arcoating/test_core.py
  nevergrad/functions/photonics/core.py
  nevergrad/functions/photonics/test_core.py
  nevergrad/parametrization/test_utils.py
  nevergrad/parametrization/utils.py
Labels: CLA Signed

#552 Store leaderboard for some challenging testbeds
  nevergrad/functions/arcoating/core.py
  nevergrad/functions/arcoating/test_core.py
  nevergrad/functions/base.py
  nevergrad/functions/leaderboard.csv
  nevergrad/functions/photonics/core.py
  nevergrad/functions/photonics/test_core.py
Labels: CLA Signed, Difficulty: Low, Priority: Low, Type: Enhancement

#548 Add an experimental rolling mutation
  nevergrad/functions/mlda/test_problems.py
  nevergrad/functions/test_base.py
  nevergrad/optimization/test_base.py
  nevergrad/parametrization/core.py
  nevergrad/parametrization/data.py
  nevergrad/parametrization/test_parameter.py
  nevergrad/parametrization/test_parameters_legacy.py
  nevergrad/parametrization/test_utils.py
  nevergrad/parametrization/utils.py
Labels: CLA Signed, Difficulty: Medium, Priority: High, Status: Review needed, Type: Enhancement

#555 Force bayes opt update in tests
  .circleci/config.yml
  nevergrad/optimization/recorded_recommendations.csv
  nevergrad/optimization/test_optimizerlib.py
Labels: CLA Signed

#554 remove dirty experiments, simplify others
  nevergrad/benchmark/experiments.py
  nevergrad/benchmark/test_experiments.py
  nevergrad/benchmark/xpbase.py
  nevergrad/functions/base.py
  nevergrad/parametrization/choice.py
Labels: CLA Signed

#557 New bo version
  requirements/main.txt
Labels: CLA Signed
