Repository facebookresearch/nevergrad, pull requests merged in 2020-03, with the labels that each got.

#546 add support for alternative cmaes implementation
  mypy.ini
  nevergrad/optimization/experimentalvariants.py
  nevergrad/optimization/optimizerlib.py
  nevergrad/optimization/recorded_recommendations.csv
  requirements/bench.txt
Labels: CLA Signed

#551 Emna
  nevergrad/benchmark/experiments.py
  nevergrad/functions/leaderboard.csv
  nevergrad/optimization/experimentalvariants.py
  nevergrad/optimization/families.py
  nevergrad/optimization/optimizerlib.py
  nevergrad/optimization/recorded_recommendations.csv
Labels: CLA Signed

#556 Record fix + nits + experiment with Translation in Photonics
  nevergrad/functions/base.py
  nevergrad/functions/leaderboard.csv
  nevergrad/functions/photonics/core.py
  nevergrad/functions/photonics/test_core.py
  nevergrad/optimization/optimizerlib.py
  nevergrad/optimization/recorded_recommendations.csv
Labels: CLA Signed, Difficulty: Low, Priority: Low, Type: Enhancement

#560 Return a standard float in Scalar
  nevergrad/parametrization/data.py
Labels: CLA Signed

#562 Update Morpho leaderboard
  nevergrad/functions/leaderboard.csv
Labels: CLA Signed

#530 DOC: Added FORCE-project reference to the hypervolume code
  nevergrad/functions/multiobjective/hypervolume.py
  nevergrad/functions/multiobjective/test_structures.py
Labels: CLA Signed

#561 Refactoring tbpsa
  nevergrad/functions/leaderboard.csv
  nevergrad/optimization/experimentalvariants.py
  nevergrad/optimization/families.py
  nevergrad/optimization/optimizerlib.py
  nevergrad/optimization/test_optimizerlib.py
Labels: CLA Signed

#563 Simpler prints for bounds
  nevergrad/functions/leaderboard.csv
  nevergrad/parametrization/data.py
  nevergrad/parametrization/test_parameter.py
  nevergrad/parametrization/test_transforms.py
  nevergrad/parametrization/transforms.py
Labels: CLA Signed

#564 Update doc with new scalar API
  docs/parametrization.rst
  nevergrad/parametrization/data.py
Labels: CLA Signed

#565 Update morpho leaderboard
  nevergrad/functions/leaderboard.csv
  nevergrad/optimization/helpers.py
  nevergrad/optimization/test_doc.py
Labels: CLA Signed

#567 Make similar configured optimizer be equal + recast fix
  nevergrad/benchmark/xpbase.py
  nevergrad/optimization/base.py
  nevergrad/optimization/recaster.py
  nevergrad/optimization/test_optimizerlib.py
Labels: CLA Signed, Difficulty: Medium, Priority: High, Type: Bug

#569 fixed type o
  docs/optimizers_ref.rst
Labels: CLA Signed

#566 New yasmallbbob
  nevergrad/benchmark/experiments.py
Labels: CLA Signed

#572 Update oneshot.py
  nevergrad/optimization/oneshot.py
Labels: CLA Signed

#573 progressive growing of optimization models
  nevergrad/benchmark/experiments.py
  nevergrad/optimization/experimentalvariants.py
  nevergrad/optimization/optimizerlib.py
  nevergrad/optimization/recorded_recommendations.csv
Labels: CLA Signed

#574 Increase coverage on functions/powersystems/core.py
  nevergrad/functions/powersystems/test_core.py
Labels: CLA Signed

#575 Allow all algorithms to recommend before starting
  nevergrad/optimization/oneshot.py
  nevergrad/optimization/optimizerlib.py
  nevergrad/optimization/recaster.py
  nevergrad/optimization/test_optimizerlib.py
  nevergrad/optimization/test_recaster.py
Labels: CLA Signed

#571 Make pruning much much less conservative
  CHANGELOG.md
  docs/contributing.rst
  nevergrad/optimization/test_utils.py
  nevergrad/optimization/utils.py
Labels: CLA Signed, Difficulty: Low, Priority: Medium, Type: Bug, Type: Enhancement

#576 Prepare for v0.4.0 release
  CHANGELOG.md
  nevergrad/__init__.py
Labels: CLA Signed, Difficulty: Low, Priority: Critical, Type: Enhancement

#577 automatic choice of the rescaling: the new version
  nevergrad/optimization/oneshot.py
  nevergrad/optimization/recorded_recommendations.csv
Labels: CLA Signed

#579 add a oneshot method combining all improvements currently in the platform
  nevergrad/optimization/oneshot.py
  nevergrad/optimization/recorded_recommendations.csv
Labels: CLA Signed

#580 cleaning Split as discussed with JR
  nevergrad/benchmark/experiments.py
  nevergrad/optimization/experimentalvariants.py
  nevergrad/optimization/optimizerlib.py
  nevergrad/optimization/recorded_recommendations.csv
Labels: CLA Signed

#584 Minor documentation fixes
  docs/conf.py
  docs/opencompetition2020.md
  docs/optimization.rst
  nevergrad/parametrization/data.py
Labels: CLA Signed

#583 Update opencompetition2020.md
  docs/opencompetition2020.md
Labels: CLA Signed

#578 Another version of EMNA (with population size adaptation)
  nevergrad/benchmark/experiments.py
  nevergrad/functions/leaderboard.csv
  nevergrad/optimization/experimentalvariants.py
  nevergrad/optimization/optimizerlib.py
  nevergrad/optimization/recorded_recommendations.csv
Labels: CLA Signed

#582 Faster fight plot + push numbers on photonics
  nevergrad/benchmark/experiments.py
  nevergrad/benchmark/plotting.py
  nevergrad/functions/leaderboard.csv
Labels: CLA Signed

#581 Convert mutations to parameters
  nevergrad/functions/arcoating/core.py
  nevergrad/functions/functionlib.py
  nevergrad/functions/photonics/core.py
  nevergrad/optimization/callbacks.py
  nevergrad/optimization/test_callbacks.py
  nevergrad/parametrization/choice.py
  nevergrad/parametrization/core.py
  nevergrad/parametrization/data.py
  nevergrad/parametrization/mutation.py
  nevergrad/parametrization/parameter.py
  nevergrad/parametrization/test_mutation.py
  nevergrad/parametrization/test_transforms.py
  nevergrad/parametrization/test_utils.py
  nevergrad/parametrization/transforms.py
  nevergrad/parametrization/utils.py
Labels: CLA Signed

#588 Fix MLDA copy
  nevergrad/functions/base.py
  nevergrad/functions/mlda/problems.py
  nevergrad/functions/mlda/test_problems.py
Labels: CLA Signed, Difficulty: Medium, Priority: High, Type: Bug

#590 Add ProgressBar callback with tqdm
  mypy.ini
  nevergrad/optimization/callbacks.py
  requirements/bench.txt
Labels: CLA Signed

#591 Update GECCO submission deadline
  docs/opencompetition2020.md
Labels: CLA Signed

#586 Allow several parametrizations on the same plot
  nevergrad/benchmark/experiments.py
  nevergrad/benchmark/plotting.py
  nevergrad/benchmark/test_plotting.py
  nevergrad/benchmark/xpbase.py
  nevergrad/functions/base.py
  nevergrad/functions/functionlib.py
  nevergrad/functions/leaderboard.csv
  nevergrad/functions/photonics/test_core.py
  nevergrad/optimization/base.py
  nevergrad/optimization/utils.py
  nevergrad/parametrization/core.py
  nevergrad/parametrization/data.py
  nevergrad/parametrization/mutation.py
  nevergrad/parametrization/test_mutation.py
  nevergrad/parametrization/test_parameter.py
  nevergrad/parametrization/test_parameters_legacy.py
Labels: CLA Signed

#595 Improve inoculation documentation
  docs/optimization.rst
  nevergrad/optimization/base.py
  nevergrad/optimization/test_doc.py
Labels: CLA Signed

#596 Add more explicit errors when setting values of containers
  nevergrad/parametrization/container.py
  nevergrad/parametrization/core.py
Labels: CLA Signed

#597 Print current value in error
  nevergrad/parametrization/core.py
Labels: CLA Signed

#598 Sample to the bounds in quasi random optimizers
  CHANGELOG.md
  nevergrad/optimization/oneshot.py
  nevergrad/optimization/test_optimizerlib.py
  nevergrad/optimization/test_utils.py
  nevergrad/optimization/utils.py
  nevergrad/parametrization/data.py
Labels: CLA Signed, Difficulty: High, Priority: High, Type: Bug

#594 Keep parameter in the archive
  CHANGELOG.md
  nevergrad/optimization/base.py
  nevergrad/optimization/mutations.py
  nevergrad/optimization/oneshot.py
  nevergrad/optimization/optimizerlib.py
  nevergrad/optimization/test_mutations.py
  nevergrad/optimization/test_utils.py
  nevergrad/optimization/utils.py
  nevergrad/parametrization/core.py
Labels: CLA Signed, Difficulty: Medium, Priority: High, Type: Enhancement, Type: Refactoring
