Repository facebookresearch/nevergrad, pull requests merged in 2020-12, with the labels that each got.

#911 Metamodel also in sequential mode
  nevergrad/optimization/optimizerlib.py
Labels: CLA Signed

#908 Clean the ngopt family
  nevergrad/optimization/optimizerlib.py
  nevergrad/optimization/recorded_recommendations.csv
  nevergrad/optimization/test_optimizerlib.py
Labels: CLA Signed

#904 Reduce optimization methods in experiments
  nevergrad/benchmark/experiments.py
  nevergrad/benchmark/optgroups.py
  nevergrad/benchmark/optimizer_groups.txt
  nevergrad/optimization/experimentalvariants.py
  nevergrad/optimization/optimizerlib.py
  nevergrad/optimization/recorded_recommendations.csv
Labels: CLA Signed

#919 Powell in metamodel solving + better tests.
  nevergrad/optimization/optimizerlib.py
  nevergrad/optimization/recorded_recommendations.csv
  nevergrad/optimization/test_optimizerlib.py
Labels: CLA Signed

#921 Reactivate IOHexperimenter
  requirements/bench.txt
Labels: CLA Signed

#914 Automatically add initialization registration of xp
  CHANGELOG.md
  docs/benchmarking.rst
  nevergrad/benchmark/additional/example.py
  nevergrad/benchmark/test_xpbase.py
  nevergrad/functions/arcoating/core.py
  nevergrad/functions/base.py
  nevergrad/functions/control/core.py
  nevergrad/functions/functionlib.py
  nevergrad/functions/games/game.py
  nevergrad/functions/images/core.py
  nevergrad/functions/iohprofiler/core.py
  nevergrad/functions/leaderboard.csv
  nevergrad/functions/mixsimulator/core.py
  nevergrad/functions/ml/mlfunctionlib.py
  nevergrad/functions/mlda/problems.py
  nevergrad/functions/pbt.py
  nevergrad/functions/photonics/core.py
  nevergrad/functions/powersystems/core.py
  nevergrad/functions/pyomo/core.py
  nevergrad/functions/rl/agents.py
  nevergrad/functions/rocket/core.py
  nevergrad/functions/stsp/core.py
  nevergrad/functions/test_base.py
Labels: CLA Signed, Difficulty: High, Priority: High, Type: Enhancement

#920 Cleaning the metamodel and the test.
  nevergrad/functions/leaderboard.csv
  nevergrad/optimization/optimizerlib.py
  nevergrad/optimization/test_optimizerlib.py
Labels: CLA Signed

#909 Add a test closer to user needs
  nevergrad/optimization/optimizerlib.py
  nevergrad/optimization/test_optimizerlib.py
Labels: CLA Signed

#917 Rescaling optimization algorithms
  nevergrad/optimization/optimizerlib.py
  nevergrad/optimization/recorded_recommendations.csv
Labels: CLA Signed, Status: Feedbacks welcomed, Status: Help wanted

#925 add a little but of budget for killing flakiness
  nevergrad/functions/leaderboard.csv
  nevergrad/optimization/test_optimizerlib.py
Labels: CLA Signed

#928 More splitters
  nevergrad/benchmark/optgroups.py
Labels: CLA Signed

#931 Fix xp function unpickling
  nevergrad/benchmark/test_xpbase.py
  nevergrad/functions/base.py
  nevergrad/functions/test_base.py
Labels: CLA Signed, Difficulty: Low, Priority: Critical, Type: Bug

#932 Add YABBOB with instrumentation for decomposable problems
  nevergrad/benchmark/experiments.py
  nevergrad/functions/functionlib.py
  nevergrad/functions/test_functionlib.py
Labels: CLA Signed

#913 Improve adversarial attacks
  nevergrad/benchmark/experiments.py
Labels: CLA Signed

#824 Adaptive step-size for discrete domains: the multivariate anisotropic case
  nevergrad/benchmark/experiments.py
  nevergrad/benchmark/optimizer_groups.txt
  nevergrad/optimization/mutations.py
  nevergrad/optimization/optimizerlib.py
  nevergrad/optimization/recorded_recommendations.csv
  nevergrad/parametrization/discretization.py
Labels: CLA Signed

#922 Switch to DE in NGOpt8 if multiobjective
  nevergrad/optimization/base.py
  nevergrad/optimization/differentialevolution.py
  nevergrad/optimization/optimizerlib.py
  nevergrad/optimization/test_optimizerlib.py
  nevergrad/parametrization/utils.py
Labels: CLA Signed

#886 Rewriting the mutator code with numpy arrays
  nevergrad/optimization/mutations.py
Labels: CLA Signed

#939 More Keras tests
  nevergrad/benchmark/experiments.py
  nevergrad/functions/ml/mlfunctionlib.py
Labels: CLA Signed

#942 Clear CI cache and bump version
  .circleci/config.yml
  nevergrad/__init__.py
Labels: CLA Signed

#943 Force update pip install
  .circleci/config.yml
  nevergrad/__init__.py
Labels: CLA Signed

#905 Score images with iqa
  mypy.ini
  nevergrad/benchmark/experiments.py
  nevergrad/benchmark/test_experiments.py
  nevergrad/common/testing.py
  nevergrad/functions/base.py
  nevergrad/functions/images/__init__.py
  nevergrad/functions/images/core.py
  nevergrad/functions/images/imagelosses.py
  nevergrad/functions/images/test_core.py
  nevergrad/functions/images/test_imagelosses.py
  requirements/bench.txt
Labels: CLA Signed

#935 Switch to DE if Powell has issues for working on the metamodel
  nevergrad/optimization/optimizerlib.py
  nevergrad/optimization/test_optimizerlib.py
Labels: CLA Signed

#945 Simplify sub-experiment code
  nevergrad/benchmark/experiments.py
  nevergrad/benchmark/optimizer_groups.txt
Labels: CLA Signed

#944 Skip unnecessary/slow Windows performance tests
  .circleci/config.yml
  nevergrad/optimization/test_optimizerlib.py
Labels: CLA Signed

#941 Even more ml sets
  nevergrad/benchmark/experiments.py
  nevergrad/functions/ml/mlfunctionlib.py
  nevergrad/functions/ml/test_mlfunctionlib.py
Labels: CLA Signed

#946 Deactivate black for some folders to ease transition
  nevergrad/functions/control/core.py
  nevergrad/functions/control/mujoco.py
  nevergrad/functions/control/test_mujoco.py
  nevergrad/functions/photonics/core.py
  nevergrad/functions/photonics/photonics.py
  nevergrad/functions/photonics/test_core.py
  pyproject.toml
Labels: CLA Signed

#927 Proposing an elitist CMA for inoculation
  nevergrad/benchmark/optgroups.py
  nevergrad/optimization/experimentalvariants.py
  nevergrad/optimization/optimizerlib.py
  nevergrad/optimization/recorded_recommendations.csv
  nevergrad/optimization/test_optimizerlib.py
Labels: CLA Signed

#695 Improve hashing xp
  nevergrad/functions/functionlib.py
  nevergrad/functions/test_functionlib.py
Labels: CLA Signed

#924 New instrumentation for photonics
  nevergrad/benchmark/experiments.py
  nevergrad/benchmark/optimizer_groups.txt
  nevergrad/functions/photonics/core.py
Labels: CLA Signed

#929 sequential or fully parallel ML.
  nevergrad/benchmark/experiments.py
Labels: CLA Signed

#923 Split optimization applied to ngopt
  nevergrad/benchmark/optgroups.py
  nevergrad/benchmark/optimizer_groups.txt
  nevergrad/optimization/experimentalvariants.py
  nevergrad/optimization/optimizerlib.py
  nevergrad/optimization/recorded_recommendations.csv
  nevergrad/optimization/test_optimizerlib.py
Labels: CLA Signed, Type: Enhancement

#930 Add a constrained counterpart of YABBOB
  nevergrad/benchmark/experiments.py
  nevergrad/parametrization/utils.py
Labels: CLA Signed

#937 Add a descriptor for non-proxy functions
  nevergrad/functions/ml/mlfunctionlib.py
  nevergrad/parametrization/test_parameter.py
  nevergrad/parametrization/utils.py
Labels: CLA Signed

#950 fixblack
  docs/conf.py
  nevergrad/benchmark/experiments.py
  nevergrad/benchmark/optgroups.py
  nevergrad/benchmark/xpbase.py
  nevergrad/functions/base.py
  nevergrad/functions/control/core.py
  nevergrad/functions/images/core.py
  nevergrad/functions/images/imagelosses.py
  nevergrad/functions/images/test_imagelosses.py
  nevergrad/functions/photonics/core.py
  nevergrad/optimization/optimizerlib.py
Labels: CLA Signed

#952 Propagate file headers
  .circleci/config.yml
  nevergrad/common/test_testing.py
  nevergrad/functions/images/imagelosses.py
  nevergrad/functions/iohprofiler/__init__.py
  nevergrad/functions/iohprofiler/core.py
  nevergrad/functions/iohprofiler/test_core.py
  nevergrad/optimization/multiobjective/nsga2.py
  nevergrad/optimization/multiobjective/test_nsga2.py
  nevergrad/optimization/recastlib.py
Labels: CLA Signed

#951 Fix unexpected recommendation
  CHANGELOG.md
  nevergrad/optimization/base.py
  nevergrad/optimization/recorded_recommendations.csv
  nevergrad/optimization/test_base.py
  nevergrad/optimization/test_utils.py
  nevergrad/optimization/utils.py
Labels: CLA Signed

#958 [PR on PR] Merge multi and mono evaluations
  nevergrad/benchmark/test_xpbase.py
  nevergrad/benchmark/xpbase.py
  nevergrad/functions/arcoating/core.py
  nevergrad/functions/arcoating/test_core.py
  nevergrad/functions/base.py
  nevergrad/functions/control/core.py
  nevergrad/functions/functionlib.py
  nevergrad/functions/games/game.py
  nevergrad/functions/images/core.py
  nevergrad/functions/images/test_core.py
  nevergrad/functions/leaderboard.csv
  nevergrad/functions/ml/mlfunctionlib.py
  nevergrad/functions/ml/test_mlfunctionlib.py
  nevergrad/functions/photonics/core.py
  nevergrad/functions/photonics/test_core.py
  nevergrad/functions/rl/agents.py
  nevergrad/functions/test_functionlib.py
Labels: CLA Signed

#953 Provide API to customize multiobjective evaluation
  nevergrad/benchmark/optimizer_groups.txt
  nevergrad/benchmark/test_xpbase.py
  nevergrad/benchmark/xpbase.py
  nevergrad/functions/arcoating/core.py
  nevergrad/functions/arcoating/test_core.py
  nevergrad/functions/base.py
  nevergrad/functions/control/core.py
  nevergrad/functions/functionlib.py
  nevergrad/functions/games/game.py
  nevergrad/functions/images/core.py
  nevergrad/functions/images/test_core.py
  nevergrad/functions/leaderboard.csv
  nevergrad/functions/ml/mlfunctionlib.py
  nevergrad/functions/ml/test_mlfunctionlib.py
  nevergrad/functions/multiobjective/core.py
  nevergrad/functions/photonics/core.py
  nevergrad/functions/photonics/test_core.py
  nevergrad/functions/rl/agents.py
  nevergrad/functions/test_functionlib.py
  nevergrad/optimization/base.py
  nevergrad/optimization/multiobjective/core.py
Labels: CLA Signed

#960 Add a check for dangereous default values
  .circleci/config.yml
Labels: CLA Signed

#961 [PR on PR] Provide a pareto experiment
  .circleci/config.yml
  nevergrad/benchmark/experiments.py
  nevergrad/benchmark/optimizer_groups.txt
  nevergrad/benchmark/test_xpbase.py
  nevergrad/benchmark/xpbase.py
  nevergrad/functions/arcoating/core.py
  nevergrad/functions/arcoating/test_core.py
  nevergrad/functions/base.py
  nevergrad/functions/control/core.py
  nevergrad/functions/functionlib.py
  nevergrad/functions/games/game.py
  nevergrad/functions/helpers.py
  nevergrad/functions/images/core.py
  nevergrad/functions/images/test_core.py
  nevergrad/functions/leaderboard.csv
  nevergrad/functions/ml/mlfunctionlib.py
  nevergrad/functions/ml/test_mlfunctionlib.py
  nevergrad/functions/multiobjective/core.py
  nevergrad/functions/photonics/core.py
  nevergrad/functions/photonics/test_core.py
  nevergrad/functions/rl/agents.py
  nevergrad/functions/test_base.py
  nevergrad/functions/test_functionlib.py
  nevergrad/optimization/base.py
  nevergrad/optimization/multiobjective/core.py
Labels: CLA Signed

#959 Seed the pareto extractor
  nevergrad/functions/base.py
  nevergrad/optimization/base.py
  nevergrad/optimization/multiobjective/core.py
Labels: CLA Signed

#963 fix keras issue
  nevergrad/functions/ml/mlfunctionlib.py
  nevergrad/functions/ml/test_mlfunctionlib.py
Labels: CLA Signed

#965 Quickfix weird new reproducibility issue
  nevergrad/benchmark/test_xpbase.py
  nevergrad/functions/base.py
  nevergrad/functions/powersystems/test_core.py
  nevergrad/functions/test_functionlib.py
  nevergrad/optimization/test_doc.py
Labels: CLA Signed

#967 [PR on brplusplus PR] Add model cache and reduce tests
  docs/conf.py
  mypy.ini
  nevergrad/benchmark/test_experiments.py
  nevergrad/benchmark/test_xpbase.py
  nevergrad/common/test_tools.py
  nevergrad/common/tools.py
  nevergrad/functions/base.py
  nevergrad/functions/helpers.py
  nevergrad/functions/images/imagelosses.py
  nevergrad/functions/images/test_core.py
  nevergrad/functions/images/test_imagelosses.py
Labels: CLA Signed

#968 [PR on cstsolve PR] Try to extract constraint solving
  nevergrad/optimization/base.py
  nevergrad/optimization/test_optimizerlib.py
  nevergrad/optimization/utils.py
  nevergrad/parametrization/choice.py
  nevergrad/parametrization/core.py
Labels: CLA Signed

#969 PR on PR for cleaning the MOO/images work.
  nevergrad/benchmark/experiments.py
  nevergrad/benchmark/test_experiments.py
  nevergrad/functions/helpers.py
  nevergrad/functions/images/imagelosses.py
  nevergrad/functions/images/test_imagelosses.py
Labels: CLA Signed

#948 More image problems, including MOO
  docs/conf.py
  mypy.ini
  nevergrad/benchmark/experiments.py
  nevergrad/benchmark/optgroups.py
  nevergrad/benchmark/optimizer_groups.txt
  nevergrad/benchmark/test_experiments.py
  nevergrad/common/test_tools.py
  nevergrad/common/tools.py
  nevergrad/functions/base.py
  nevergrad/functions/helpers.py
  nevergrad/functions/images/core.py
  nevergrad/functions/images/imagelosses.py
  nevergrad/functions/images/test_core.py
  nevergrad/functions/images/test_imagelosses.py
  nevergrad/functions/leaderboard.csv
  nevergrad/functions/test_base.py
  nevergrad/optimization/multiobjective/core.py
  requirements/bench.txt
Labels: CLA Signed

#971 Tighter tests still pass without flakiness
  nevergrad/optimization/test_optimizerlib.py
Labels: CLA Signed

#962 Limit to 100 images in adversarial_attacks
  nevergrad/functions/images/core.py
Labels: CLA Signed

#974 remove default_optims, improve optgroups, add new ngopt
  nevergrad/benchmark/experiments.py
  nevergrad/benchmark/optgroups.py
  nevergrad/benchmark/optimizer_groups.txt
  nevergrad/optimization/optimizerlib.py
  nevergrad/optimization/recorded_recommendations.csv
  nevergrad/optimization/test_optimizerlib.py
Labels: CLA Signed

#980 update leaderboard
  nevergrad/functions/leaderboard.csv
Labels: CLA Signed

#978 docs: fix simple typo, propotional -> proportional
  nevergrad/optimization/optimizerlib.py
Labels: CLA Signed

#981 Adding seeds in experiments/get_optimizers
  nevergrad/benchmark/experiments.py
Labels: CLA Signed

#982 Update test_experiments.py
  nevergrad/benchmark/test_experiments.py
Labels: CLA Signed

#983 Fteytaud fix
  nevergrad/benchmark/experiments.py
Labels: CLA Signed

#984 Adding "proxy" descriptor
  nevergrad/benchmark/experiments.py
  nevergrad/benchmark/test_experiments.py
  nevergrad/functions/helpers.py
Labels: CLA Signed

#975 Moving Pgan into the generic image class and improving coverage
  nevergrad/benchmark/experiments.py
  nevergrad/benchmark/test_experiments.py
  nevergrad/functions/helpers.py
  nevergrad/functions/images/core.py
  nevergrad/functions/images/imagelosses.py
  nevergrad/functions/leaderboard.csv
  nevergrad/functions/ml/mlfunctionlib.py
  nevergrad/optimization/test_optimizerlib.py
Labels: CLA Signed

#987 Wip master into cspsolve2
  docs/conf.py
  mypy.ini
  nevergrad/benchmark/experiments.py
  nevergrad/benchmark/optgroups.py
  nevergrad/benchmark/optimizer_groups.txt
  nevergrad/benchmark/test_experiments.py
  nevergrad/common/test_tools.py
  nevergrad/common/tools.py
  nevergrad/functions/base.py
  nevergrad/functions/helpers.py
  nevergrad/functions/images/core.py
  nevergrad/functions/images/imagelosses.py
  nevergrad/functions/images/test_core.py
  nevergrad/functions/images/test_imagelosses.py
  nevergrad/functions/leaderboard.csv
  nevergrad/functions/ml/mlfunctionlib.py
  nevergrad/functions/test_base.py
  nevergrad/optimization/multiobjective/core.py
  nevergrad/optimization/optimizerlib.py
  nevergrad/optimization/recorded_recommendations.csv
  nevergrad/optimization/test_optimizerlib.py
  requirements/bench.txt
Labels: CLA Signed

#989 Replace hardcoded stuff by optgroups.
  nevergrad/benchmark/experiments.py
  nevergrad/benchmark/optgroups.py
Labels: CLA Signed
