Repository facebookresearch/nevergrad, pull requests merged in 2020-07, with the labels that each got.

#748 Check type pickling
  nevergrad/benchmark/optgroups.py
  nevergrad/benchmark/xpbase.py
  nevergrad/common/test_decorators.py
  nevergrad/functions/corefuncs.py
  nevergrad/optimization/base.py
  nevergrad/optimization/sequences.py
  nevergrad/optimization/test_mutations.py
  nevergrad/optimization/test_utils.py
  nevergrad/optimization/utils.py
Labels: CLA Signed

#752 Fix portfolios
  .circleci/config.yml
  docs/parametrization.rst
  nevergrad/optimization/base.py
  nevergrad/optimization/optimizerlib.py
  nevergrad/optimization/recorded_recommendations.csv
  nevergrad/parametrization/test_instantiate.py
  nevergrad/parametrization/test_utils.py
Labels: CLA Signed, Difficulty: Medium, Priority: Critical, Type: Bug

#755 Fix CI
  .circleci/config.yml
  nevergrad/benchmark/test_experiments.py
  nevergrad/optimization/__init__.py
  nevergrad/parametrization/test_instantiate.py
Labels: Difficulty: High, Priority: Critical, Type: Bug

#753 Adding references to external use cases
  docs/machinelearning.rst
Labels: CLA Signed

#757 Fix small documentation typo
  docs/benchmarking.rst
Labels: CLA Signed

#750 update experiments.py: plenty of docs.
  nevergrad/benchmark/experiments.py
Labels: CLA Signed

#743 polycma: 20 CMA in parallel
  nevergrad/benchmark/experiments.py
  nevergrad/benchmark/optgroups.py
  nevergrad/optimization/optimizerlib.py
  nevergrad/optimization/recorded_recommendations.csv
Labels: CLA Signed

#729 population-based training inside Nevergrad with full compatibility with all parallel optimization methods, first xp.
  nevergrad/benchmark/experiments.py
  nevergrad/functions/__init__.py
  nevergrad/functions/functionlib.py
  nevergrad/functions/pbt.py
  nevergrad/functions/test_functionlib.py
Labels: CLA Signed

#758 itercases for PBT
  nevergrad/functions/pbt.py
Labels: CLA Signed

#760 Fix BO ordering issue
  nevergrad/optimization/optimizerlib.py
  nevergrad/optimization/test_optimizerlib.py
Labels: CLA Signed, Difficulty: Medium, Priority: Medium, Type: Bug

#715 Better plotting when there are distinct instrumentations.
  nevergrad/benchmark/experiments.py
  nevergrad/benchmark/plotting.py
  nevergrad/functions/leaderboard.csv
Labels: CLA Signed

#766 Use default method for Log bounds
  nevergrad/__init__.py
  nevergrad/parametrization/data.py
  nevergrad/parametrization/test_parameter.py
  nevergrad/parametrization/test_parameters_legacy.py
Labels: CLA Signed, Difficulty: Low, Priority: Medium, Type: Bug

#767 Fixed the spelling of advised
  nevergrad/parametrization/core.py
  nevergrad/parametrization/data.py
  nevergrad/parametrization/test_param_doc.py
Labels: CLA Signed

#768 update experiments & plotting
  nevergrad/benchmark/experiments.py
  nevergrad/benchmark/plotting.py
Labels: CLA Signed

#726 NGOpt new version
  nevergrad/optimization/optimizerlib.py
  nevergrad/optimization/recorded_recommendations.csv
Labels: CLA Signed

#771 adding tell not asked capabilities in NGOpt, at least in some cases.
  nevergrad/optimization/optimizerlib.py
  nevergrad/optimization/recorded_recommendations.csv
  nevergrad/optimization/test_optimizerlib.py
Labels: CLA Signed

#770 Renaming algorithms for readability
  nevergrad/benchmark/experiments.py
  nevergrad/optimization/experimentalvariants.py
  nevergrad/optimization/optimizerlib.py
  nevergrad/optimization/recorded_recommendations.csv
Labels: CLA Signed

#772 Improve typing consistency and simplicity
  docs/contributing.rst
  nevergrad/__init__.py
  nevergrad/benchmark/__main__.py
  nevergrad/benchmark/core.py
  nevergrad/benchmark/execution.py
  nevergrad/benchmark/frozenexperiments.py
  nevergrad/benchmark/optimizer_groups.txt
  nevergrad/benchmark/plotting.py
  nevergrad/benchmark/test_execution.py
  nevergrad/benchmark/test_xpbase.py
  nevergrad/benchmark/utils.py
  nevergrad/common/decorators.py
  nevergrad/common/test_decorators.py
  nevergrad/common/typetools.py
  nevergrad/common/typing.py
  nevergrad/functions/arcoating/core.py
  nevergrad/functions/corefuncs.py
  nevergrad/functions/functionlib.py
  nevergrad/functions/mlda/datasets.py
  nevergrad/functions/mlda/problems.py
  nevergrad/functions/mlda/test_datasets.py
  nevergrad/functions/multiobjective/core.py
  nevergrad/functions/rl/agents.py
  nevergrad/functions/rl/base.py
  nevergrad/functions/rl/envs.py
  nevergrad/functions/rl/test_envs.py
  nevergrad/functions/test_functionlib.py
  nevergrad/optimization/base.py
  nevergrad/optimization/mutations.py
  nevergrad/optimization/oneshot.py
  nevergrad/optimization/optimizerlib.py
  nevergrad/optimization/recaster.py
  nevergrad/optimization/recastlib.py
  nevergrad/optimization/sequences.py
  nevergrad/optimization/test_base.py
  nevergrad/optimization/test_callbacks.py
  nevergrad/optimization/test_mutations.py
  nevergrad/optimization/test_optimizerlib.py
  nevergrad/optimization/test_recaster.py
  nevergrad/optimization/test_sequences.py
  nevergrad/optimization/utils.py
  nevergrad/parametrization/choice.py
  nevergrad/parametrization/core.py
  nevergrad/parametrization/data.py
  nevergrad/parametrization/discretization.py
  nevergrad/parametrization/instantiate.py
  nevergrad/parametrization/test_discretization.py
  nevergrad/parametrization/test_transforms.py
  nevergrad/parametrization/transforms.py
Labels: CLA Signed

#773 fix the fake creation of an optimizer with b=100
  nevergrad/optimization/optimizerlib.py
Labels: CLA Signed

#777 Better fix for insufficient budget
  nevergrad/optimization/optimizerlib.py
Labels: CLA Signed
