Repository facebookresearch/nevergrad, pull requests merged in 2020-06, with the labels that each got.

#705 Fix Changelog dates
  CHANGELOG.md
  docs/conf.py
Labels: CLA Signed

#707 Move pyproj requirement to bench.txt
  nevergrad/functions/__init__.py
  requirements/bench.txt
  requirements/main.txt
Labels: CLA Signed

#708 Default to bouncing constr in Photonics
  nevergrad/functions/arcoating/core.py
  nevergrad/functions/arcoating/test_core.py
  nevergrad/functions/photonics/core.py
Labels: CLA Signed

#711 Make ProgressBar callback picklable
  docs/optimizers_ref.rst
  nevergrad/optimization/callbacks.py
  nevergrad/optimization/test_callbacks.py
Labels: CLA Signed, Difficulty: Low, Priority: Medium, Type: Bug

#713 Discrete BrainStormOptimization
  nevergrad/optimization/optimizerlib.py
  nevergrad/optimization/recorded_recommendations.csv
Labels: CLA Signed

#712 Fix dim1 bug in mutations
  nevergrad/optimization/mutations.py
  nevergrad/optimization/test_optimizerlib.py
Labels: CLA Signed, Difficulty: Low, Priority: Medium, Type: Bug

#717 Start logging optimizer info
  nevergrad/optimization/optimizerlib.py
  nevergrad/optimization/test_optimizerlib.py
Labels: CLA Signed, Difficulty: Medium, Priority: Medium, Type: Enhancement

#723 Allow setting const Array
  nevergrad/parametrization/core.py
  nevergrad/parametrization/test_parameter.py
Labels: CLA Signed, Difficulty: Low, Priority: Medium, Type: Bug

#722 Ctulo2
  nevergrad/benchmark/experiments.py
  nevergrad/optimization/optimizerlib.py
  nevergrad/optimization/recorded_recommendations.csv
  nevergrad/optimization/test_optimizerlib.py
  nevergrad/parametrization/parameter.py
Labels: CLA Signed

#719 Adding Shiwa in some experiments
  nevergrad/benchmark/experiments.py
Labels: CLA Signed

#525 Design optimizer groups for benchmarks
  nevergrad/benchmark/experiments.py
  nevergrad/benchmark/optgroups.py
  nevergrad/benchmark/optimizer_groups.txt
  nevergrad/benchmark/test_experiments.py
  nevergrad/optimization/base.py
Labels: CLA Signed

#725 Switch doc to NGO rather than 1+1
  README.md
Labels: CLA Signed

#727 Update optimizer documentation
  nevergrad/optimization/differentialevolution.py
  nevergrad/optimization/optimizerlib.py
  nevergrad/optimization/recastlib.py
Labels: CLA Signed

#728 NGOptimization adapted to multi-/many-objective cases
  nevergrad/benchmark/experiments.py
  nevergrad/optimization/optimizerlib.py
  nevergrad/parametrization/utils.py
Labels: CLA Signed

#730 a hd multimodal bench
  nevergrad/benchmark/experiments.py
Labels: CLA Signed

#731 chaining: reporting the archive to next optim
  nevergrad/optimization/recastlib.py
  nevergrad/optimization/recorded_recommendations.csv
Labels: CLA Signed

#732 global xp plot aggregating all cases
  nevergrad/benchmark/plotting.py
  nevergrad/benchmark/test_plotting.py
Labels: CLA Signed

#740 better normalization
  nevergrad/benchmark/plotting.py
Labels: CLA Signed

#745 Add a normalization on cases for plotting
  nevergrad/benchmark/plotting.py
  nevergrad/benchmark/test_plotting.py
Labels: CLA Signed

#747 Solve pickling error after archive pruning
  nevergrad/optimization/base.py
  nevergrad/optimization/test_utils.py
  nevergrad/optimization/utils.py
Labels: CLA Signed
