Repository facebookresearch/nevergrad, pull requests merged in 2020-05, with the labels that each got.

#639 Update CONTRIBUTING and PR template
  .github/CONTRIBUTING.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: CLA Signed

#637 wider wide_discrete
  nevergrad/benchmark/experiments.py
Labels: CLA Signed

#636 Adding a collaborative coevolution in high-dimension optimization
  nevergrad/benchmark/experiments.py
Labels: CLA Signed

#642 ML test cases: new version
  nevergrad/benchmark/experiments.py
  nevergrad/functions/ml/__init__.py
  nevergrad/functions/ml/mlfunctionlib.py
  nevergrad/functions/ml/test_mlfunctionlib.py
  nevergrad/functions/test_functionlib.py
Labels: CLA Signed

#643 Adding the regression tree criterion
  nevergrad/benchmark/experiments.py
  nevergrad/functions/ml/mlfunctionlib.py
Labels: CLA Signed

#644 Deactivate full range sampling if init provided
  nevergrad/parametrization/data.py
  nevergrad/parametrization/test_parameter.py
Labels: CLA Signed

#645 Extending ML problems
  nevergrad/benchmark/experiments.py
  nevergrad/functions/ml/mlfunctionlib.py
  nevergrad/functions/ml/test_mlfunctionlib.py
Labels: CLA Signed

#650 Prepare for version 0.4.1
  CHANGELOG.md
  nevergrad/__init__.py
Labels: CLA Signed, Difficulty: Low, Priority: Low

#649 Better organization of datasets.
  nevergrad/functions/ml/mlfunctionlib.py
  nevergrad/functions/ml/test_mlfunctionlib.py
Labels: CLA Signed

#648 Better descriptors.
  nevergrad/benchmark/experiments.py
  nevergrad/functions/ml/mlfunctionlib.py
Labels: CLA Signed

#651 Adding boston and diabetes and more artificial
  nevergrad/benchmark/experiments.py
  nevergrad/functions/functionlib.py
  nevergrad/functions/ml/mlfunctionlib.py
  nevergrad/functions/ml/test_mlfunctionlib.py
Labels: CLA Signed

#653 Remove debug output
  nevergrad/benchmark/experiments.py
Labels: CLA Signed

#654 Faster because less object creation.
  nevergrad/benchmark/experiments.py
Labels: CLA Signed

#656 Faster for slow experiments.
  nevergrad/benchmark/test_experiments.py
Labels: CLA Signed

#658 remove useless dependency.
  requirements/bench.txt
Labels: CLA Signed

#659 fix minor issues in rocket.py
  nevergrad/functions/rocket/core.py
  nevergrad/functions/rocket/rocket.py
Labels: CLA Signed

#661 Shortening tests.
  nevergrad/benchmark/test_experiments.py
Labels: CLA Signed

#662 Reduce test cost.
  nevergrad/benchmark/test_experiments.py
Labels: CLA Signed

#663 remove mutDE from test
  nevergrad/optimization/test_optimizerlib.py
Labels: CLA Signed

#664 fix broken link
  docs/benchmarks.rst
Labels: CLA Signed

#652 Exit test at first fail
  .circleci/config.yml
Labels: CLA Signed

#655 Add an overfitting parameter
  nevergrad/benchmark/experiments.py
  nevergrad/benchmark/test_experiments.py
  nevergrad/functions/ml/mlfunctionlib.py
Labels: CLA Signed

#665 add mutDE, but allow 3 attempts.
  nevergrad/optimization/test_optimizerlib.py
Labels: CLA Signed

#666 Handle nan recommendations in plotting
  nevergrad/benchmark/plotting.py
  nevergrad/benchmark/test_plotting.py
Labels: Difficulty: Low, Priority: Medium, Type: Bug

#647 Allow lists as input in Photonics
  nevergrad/functions/photonics/core.py
Labels: CLA Signed, Difficulty: Low, Priority: Low, Type: Enhancement

#668 Recommend a candidate when possible
  CHANGELOG.md
  nevergrad/optimization/base.py
  nevergrad/optimization/differentialevolution.py
  nevergrad/optimization/oneshot.py
  nevergrad/optimization/optimizerlib.py
  nevergrad/optimization/recaster.py
  nevergrad/optimization/recorded_recommendations.csv
  nevergrad/optimization/test_optimizerlib.py
Labels: CLA Signed

#667 Improve test/typing/style/doc for MLTuning
  mypy.ini
  nevergrad/benchmark/experiments.py
  nevergrad/functions/ml/mlfunctionlib.py
  nevergrad/functions/ml/test_mlfunctionlib.py
Labels: CLA Signed, Difficulty: Low, Priority: Medium, Type: Enhancement

#635 check suggest
  nevergrad/optimization/test_optimizerlib.py
Labels: CLA Signed

#671 Fix missing overfitting parameter
  nevergrad/benchmark/experiments.py
Labels: CLA Signed

#669 Add basic Pylint tests
  .circleci/config.yml
  nevergrad/benchmark/experiments.py
  nevergrad/benchmark/plotting.py
  nevergrad/functions/images/core.py
  nevergrad/functions/images/test_core.py
  nevergrad/optimization/oneshot.py
  requirements/dev.txt
Labels: Difficulty: Low, Priority: Medium, Type: Enhancement

#670 Allow repetitions for Choice parameters
  .circleci/config.yml
  .pylintrc
  CHANGELOG.md
  nevergrad/functions/corefuncs.py
  nevergrad/functions/leaderboard.csv
  nevergrad/functions/test_base.py
  nevergrad/functions/test_corefuncs.py
  nevergrad/parametrization/choice.py
  nevergrad/parametrization/discretization.py
  nevergrad/parametrization/test_discretization.py
  nevergrad/parametrization/test_parameter.py
  nevergrad/parametrization/test_parameters_legacy.py
Labels: CLA Signed, Difficulty: High, Priority: High, Status: In Progess, Type: Enhancement

#676 Fix repeated Choice hash
  nevergrad/__init__.py
  nevergrad/parametrization/choice.py
  nevergrad/parametrization/test_parameter.py
Labels: CLA Signed, Difficulty: Low, Priority: High, Type: Bug

#678 Deactivate BO test for windows
  nevergrad/common/testing.py
  nevergrad/optimization/test_optimizerlib.py
Labels: CLA Signed

#673 Lazy initialization in MLTuning
  nevergrad/functions/ml/mlfunctionlib.py
  nevergrad/optimization/optimizerlib.py
Labels: CLA Signed, Difficulty: Low, Priority: Medium, Type: Enhancement

#681 fix case of max mutation ratio = 1
  nevergrad/optimization/mutations.py
Labels: CLA Signed

#679 Fix discrete mutation in dim 1
  nevergrad/optimization/mutations.py
  nevergrad/optimization/test_optimizerlib.py
Labels: CLA Signed

#672 Simplify NGO/Shiwa optim attribute
  nevergrad/optimization/optimizerlib.py
  nevergrad/optimization/test_doc.py
Labels: CLA Signed, Difficulty: Low, Priority: Low, Type: Enhancement

#684 Add an experimental bouncing bounding method
  nevergrad/parametrization/data.py
  nevergrad/parametrization/test_parameter.py
  nevergrad/parametrization/test_transforms.py
  nevergrad/parametrization/transforms.py
Labels: CLA Signed, Difficulty: Low, Priority: Medium, Type: Enhancement

#688 Tuto for windows users
  README.md
  docs/getting_started.rst
  docs/index.rst
  docs/resources/windows_screenshots/CtrlWindowsAlt.jpg
  docs/resources/windows_screenshots/PR.PNG
  docs/resources/windows_screenshots/anacondanavigator.PNG
  docs/resources/windows_screenshots/commit.PNG
  docs/resources/windows_screenshots/create.PNG
  docs/resources/windows_screenshots/navigator.PNG
  docs/resources/windows_screenshots/newBranch.PNG
  docs/resources/windows_screenshots/prompt.PNG
  docs/resources/windows_screenshots/spyder.PNG
  docs/windows.md
Labels: CLA Signed

#692 updateMetaModel
  nevergrad/optimization/optimizerlib.py
Labels: CLA Signed

#690 yet another shortening
  nevergrad/benchmark/experiments.py
Labels: CLA Signed

#691 Make bouncing the default for constraints
  CHANGELOG.md
  nevergrad/parametrization/data.py
Labels: CLA Signed, Difficulty: Low, Priority: Medium, Type: Breaking changes, Type: Enhancement

#694 Deactivate seed test for too slow mltuning xp
  nevergrad/benchmark/test_experiments.py
Labels: CLA Signed

#674 First generic Meta-Model in Nevergrad
  nevergrad/benchmark/experiments.py
  nevergrad/optimization/optimizerlib.py
  nevergrad/optimization/recorded_recommendations.csv
  nevergrad/optimization/utils.py
Labels: CLA Signed

#689 Faster xp
  nevergrad/benchmark/experiments.py
Labels: CLA Signed

#697 fix rocket
  nevergrad/functions/rocket/rocket.py
Labels: CLA Signed

#696 Add TransitionChoice with repetitions
  CHANGELOG.md
  nevergrad/parametrization/choice.py
  nevergrad/parametrization/data.py
  nevergrad/parametrization/test_parameter.py
  nevergrad/parametrization/test_parameters_legacy.py
  nevergrad/parametrization/test_transforms.py
  nevergrad/parametrization/transforms.py
Labels: CLA Signed

#698 Third possibility for discrete
  nevergrad/benchmark/experiments.py
Labels: CLA Signed

#699 Deactivate ML tuning CI
  nevergrad/benchmark/test_experiments.py
Labels: CLA Signed

#700 Skip CI tests for BO
  nevergrad/optimization/test_optimizerlib.py
Labels: CLA Signed

#660 Adding a rocket simulator.
  mypy.ini
  nevergrad/benchmark/experiments.py
  nevergrad/benchmark/test_experiments.py
  nevergrad/functions/__init__.py
  nevergrad/functions/rocket/__init__.py
  nevergrad/functions/rocket/core.py
  nevergrad/functions/rocket/rocket.py
  nevergrad/functions/rocket/test_core.py
  nevergrad/optimization/test_optimizerlib.py
  requirements/main.txt
Labels: CLA Signed

#702 Update competition deadline
  docs/opencompetition2020.md
Labels: CLA Signed
