Repository facebookresearch/nevergrad, pull requests merged in 2020-04, with the labels that each got.

#593 extended deadline
  docs/opencompetition2020.md
Labels: CLA Signed

#599 Use Parameter in OnePlusOne
  CHANGELOG.md
  nevergrad/benchmark/experiments.py
  nevergrad/optimization/optimizerlib.py
  nevergrad/optimization/test_callbacks.py
Labels: CLA Signed

#603 Update Photonics leaderboard
  nevergrad/benchmark/experiments.py
  nevergrad/functions/leaderboard.csv
  nevergrad/parametrization/mutation.py
  nevergrad/parametrization/test_mutation.py
Labels: CLA Signed

#601 Implement automatic deployement
  .circleci/config.yml
  .pre-commit-config.yaml
  nevergrad/__init__.py
  setup.py
Labels: CLA Signed, Difficulty: Low, Priority: Low, Type: Enhancement

#605 Build on tags
  .circleci/config.yml
  nevergrad/__init__.py
Labels: CLA Signed

#606 Update setuptools for deployment
  .circleci/config.yml
  nevergrad/__init__.py
  requirements/dev.txt
Labels: CLA Signed

#607 Improve parametrization doc
  docs/parametrization.rst
  nevergrad/optimization/test_doc.py
  nevergrad/parametrization/core.py
  nevergrad/parametrization/test_param_doc.py
Labels: CLA Signed

#608 Restore environment for deployment
  .circleci/config.yml
  nevergrad/__init__.py
Labels: CLA Signed

#609 Make pandas a non-necessary requirement
  CHANGELOG.md
  nevergrad/benchmark/__main__.py
  nevergrad/benchmark/core.py
  nevergrad/benchmark/experiments.py
  nevergrad/benchmark/plotting.py
  nevergrad/benchmark/test_core.py
  nevergrad/benchmark/test_experiments.py
  nevergrad/benchmark/test_plotting.py
  nevergrad/benchmark/test_utils.py
  nevergrad/benchmark/utils.py
  nevergrad/common/test_tools.py
  nevergrad/common/tools.py
  nevergrad/functions/base.py
  requirements/bench.txt
  requirements/dev.txt
  requirements/main.txt
Labels: CLA Signed

#610 Fixed typo
  docs/getting_started.rst
Labels: CLA Signed

#613 Update oneshot.py
  nevergrad/optimization/oneshot.py
Labels: CLA Signed

#614 Allow specifying smaller popsize in TBPSA/EMNA/DE
  nevergrad/optimization/differentialevolution.py
  nevergrad/optimization/optimizerlib.py
Labels: CLA Signed

#615 Allow popsize for PSO
  nevergrad/optimization/optimizerlib.py
Labels: CLA Signed

#619 Enable parent tracking with CMA-ES
  nevergrad/optimization/differentialevolution.py
  nevergrad/optimization/optimizerlib.py
Labels: CLA Signed, Difficulty: Low, Priority: Medium, Type: Enhancement

#602 Update experiments.py
  nevergrad/benchmark/experiments.py
Labels: CLA Signed

#600 Platform update
  nevergrad/benchmark/experiments.py
  nevergrad/benchmark/plotting.py
  nevergrad/optimization/experimentalvariants.py
  nevergrad/optimization/oneshot.py
  nevergrad/optimization/optimizerlib.py
  nevergrad/optimization/recorded_recommendations.csv
Labels: CLA Signed

#630 Add arity descriptor in xp
  .circleci/config.yml
  nevergrad/benchmark/experiments.py
  nevergrad/benchmark/test_core.py
  nevergrad/functions/multiobjective/core.py
  nevergrad/optimization/utils.py
  requirements/dev.txt
Labels: CLA Signed

#623 Remove plenty of experimental variants
  nevergrad/benchmark/experiments.py
  nevergrad/optimization/experimentalvariants.py
  nevergrad/optimization/recorded_recommendations.csv
Labels: CLA Signed

#620 Tentatively fix EDA variants (more work to do)
  nevergrad/optimization/optimizerlib.py
  nevergrad/optimization/recorded_recommendations.csv
  nevergrad/optimization/test_optimizerlib.py
Labels: CLA Signed

#628 commenting PBIL, which is buggy, until I fix it
  nevergrad/optimization/optimizerlib.py
  nevergrad/optimization/test_optimizerlib.py
Labels: CLA Signed

#627 [WIP]prune descriptors
  nevergrad/benchmark/plotting.py
Labels: CLA Signed

#633 Add arity in descriptors
  nevergrad/benchmark/experiments.py
  nevergrad/functions/base.py
Labels: CLA Signed

#632 Add a parametrization example in the main README
  README.md
  docs/index.rst
  nevergrad/optimization/test_doc.py
  nevergrad/parametrization/test_param_doc.py
Labels: CLA Signed

#624 Add a first test case on images
  mypy.ini
  nevergrad/benchmark/experiments.py
  nevergrad/functions/images/__init__.py
  nevergrad/functions/images/core.py
  nevergrad/functions/images/headrgb_olivier.png
  nevergrad/functions/images/test_core.py
  requirements/bench.txt
Labels: CLA Signed

#634 shiva_to_shiwa
  nevergrad/benchmark/experiments.py
  nevergrad/functions/powersystems/test_core.py
  nevergrad/optimization/optimizerlib.py
  nevergrad/optimization/recorded_recommendations.csv
Labels: CLA Signed
