Repository facebookresearch/nevergrad, pull requests merged in 2020-08, with the labels that each got.

#784 Release version 0.4.2
  CHANGELOG.md
  nevergrad/__init__.py
Labels: CLA Signed

#774 Rename value to loss
  CHANGELOG.md
  nevergrad/common/typing.py
  nevergrad/optimization/base.py
  nevergrad/optimization/optimizerlib.py
  nevergrad/optimization/test_base.py
Labels: CLA Signed, Difficulty: Low, Priority: Medium, Type: Enhancement

#785 Rename to type hint FloatLoss for now
  nevergrad/common/typing.py
  nevergrad/optimization/base.py
  nevergrad/optimization/optimizerlib.py
Labels: CLA Signed

#786 Fix erroneous RL test
  nevergrad/functions/rl/agents.py
  nevergrad/functions/rl/test_agents.py
Labels: CLA Signed

#775 [Experimental] Enable multiobjective within optimizers
  CHANGELOG.md
  docs/machinelearning.rst
  docs/optimization.rst
  nevergrad/benchmark/experiments.py
  nevergrad/benchmark/test_execution.py
  nevergrad/benchmark/test_xpbase.py
  nevergrad/benchmark/xpbase.py
  nevergrad/common/typing.py
  nevergrad/functions/arcoating/core.py
  nevergrad/functions/base.py
  nevergrad/functions/functionlib.py
  nevergrad/functions/multiobjective/core.py
  nevergrad/functions/photonics/core.py
  nevergrad/functions/test_base.py
  nevergrad/functions/test_functionlib.py
  nevergrad/optimization/base.py
  nevergrad/optimization/multiobjective/__init__.py
  nevergrad/optimization/multiobjective/core.py
  nevergrad/optimization/multiobjective/hypervolume.py
  nevergrad/optimization/multiobjective/test_core.py
  nevergrad/optimization/multiobjective/test_hypervolume.py
  nevergrad/optimization/test_base.py
  nevergrad/parametrization/core.py
  nevergrad/parametrization/parameter.py
Labels: Difficulty: High, Priority: Medium, Status: In Progess, Type: Enhancement

#787 Add a parallel small budget xp
  nevergrad/benchmark/experiments.py
Labels: CLA Signed

#769 Add initial pyomo support
  docs/index.rst
  docs/pyomo.rst
  mypy.ini
  nevergrad/functions/pyomo/__init__.py
  nevergrad/functions/pyomo/core.py
  nevergrad/functions/pyomo/test_core.py
  nevergrad/functions/pyomo/test_model_1.dat
  nevergrad/functions/pyomo/test_pyomo_doc.py
  requirements/bench.txt
Labels: CLA Signed, Difficulty: High, Priority: Medium, Type: Enhancement

#789 Add a multiobjective adaptation for DE
  .circleci/config.yml
  CHANGELOG.md
  docs/optimization.rst
  nevergrad/benchmark/experiments.py
  nevergrad/benchmark/plotting.py
  nevergrad/benchmark/test_xpbase.py
  nevergrad/benchmark/xpbase.py
  nevergrad/optimization/base.py
  nevergrad/optimization/callbacks.py
  nevergrad/optimization/differentialevolution.py
  nevergrad/optimization/multiobjective/__init__.py
  nevergrad/optimization/multiobjective/core.py
  nevergrad/optimization/multiobjective/test_core.py
  nevergrad/optimization/multiobjective/test_hypervolume.py
  nevergrad/optimization/recorded_recommendations.csv
  nevergrad/optimization/test_callbacks.py
Labels: Difficulty: Medium, Priority: Medium, Type: Enhancement

#791 Include tuple in one of the examples
  docs/parametrization.rst
  nevergrad/optimization/test_doc.py
Labels: CLA Signed

#788 Improve pyomo typing
  nevergrad/functions/pyomo/core.py
  nevergrad/functions/pyomo/test_core.py
  nevergrad/functions/pyomo/test_pyomo_doc.py
Labels: CLA Signed, Difficulty: Low, Priority: Low, Type: Enhancement

#778 new NGOpt variant
  nevergrad/optimization/optimizerlib.py
  nevergrad/optimization/recorded_recommendations.csv
Labels: CLA Signed

#646 Add adversarial examples
  mypy.ini
  nevergrad/benchmark/experiments.py
  nevergrad/benchmark/test_experiments.py
  nevergrad/functions/images/__init__.py
  nevergrad/functions/images/core.py
  nevergrad/functions/images/test_core.py
  nevergrad/optimization/optimizerlib.py
  nevergrad/optimization/test_sequences.py
  requirements/bench.txt
Labels: CLA Signed
