Repository facebookresearch/nevergrad, pull requests merged in 2021-02, with the labels that each got.

#1030 Propagate black to control benchmark and experiments file
  .pylintrc
  nevergrad/benchmark/experiments.py
  nevergrad/functions/control/core.py
  nevergrad/functions/control/mujoco.py
  nevergrad/functions/control/test_mujoco.py
  nevergrad/functions/rl/__init__.py
  pyproject.toml
Labels: CLA Signed

#1031 Create a dedicated errors module
  CHANGELOG.md
  nevergrad/__init__.py
  nevergrad/benchmark/test_core.py
  nevergrad/benchmark/xpbase.py
  nevergrad/common/errors.py
  nevergrad/common/testing.py
  nevergrad/optimization/base.py
  nevergrad/optimization/differentialevolution.py
  nevergrad/optimization/es.py
  nevergrad/optimization/multiobjective/test_core.py
  nevergrad/optimization/optimizerlib.py
  nevergrad/optimization/recaster.py
  nevergrad/optimization/test_optimizerlib.py
Labels: CLA Signed

#1029 Improve container parameters API
  nevergrad/benchmark/experiments.py
  nevergrad/common/typing.py
  nevergrad/optimization/utils.py
  nevergrad/parametrization/choice.py
  nevergrad/parametrization/container.py
  nevergrad/parametrization/core.py
  nevergrad/parametrization/helpers.py
  nevergrad/parametrization/parameter.py
  nevergrad/parametrization/test_parameter.py
Labels: CLA Signed

#1033 Remove Multiobjective function
  CHANGELOG.md
  nevergrad/common/errors.py
  nevergrad/functions/functionlib.py
  nevergrad/functions/multiobjective/__init__.py
  nevergrad/functions/multiobjective/core.py
  nevergrad/functions/multiobjective/test_core.py
  nevergrad/optimization/base.py
Labels: CLA Signed

#1036 Split Array and Float structures
  CHANGELOG.md
  nevergrad/common/typing.py
  nevergrad/functions/test_functionlib.py
  nevergrad/optimization/callbacks.py
  nevergrad/optimization/utils.py
  nevergrad/parametrization/choice.py
  nevergrad/parametrization/data.py
  nevergrad/parametrization/helpers.py
  nevergrad/parametrization/mutation.py
  nevergrad/parametrization/parameter.py
  nevergrad/parametrization/test_parameter.py
  nevergrad/parametrization/utils.py
Labels: CLA Signed

#1038 Use a value descriptor/property in Parameter
  CHANGELOG.md
  nevergrad/parametrization/choice.py
  nevergrad/parametrization/container.py
  nevergrad/parametrization/core.py
  nevergrad/parametrization/data.py
Labels: CLA Signed

#1034 Update chainings name for consistency
  nevergrad/benchmark/experiments.py
  nevergrad/optimization/base.py
  nevergrad/optimization/experimentalvariants.py
  nevergrad/optimization/optimizerlib.py
  nevergrad/optimization/recorded_recommendations.csv
  nevergrad/optimization/test_optimizerlib.py
Labels: CLA Signed

#1035 Default to NSGA2 in ES multiobj + remove unused API
  CHANGELOG.md
  nevergrad/optimization/es.py
  nevergrad/optimization/multiobjective/nsga2.py
  nevergrad/optimization/multiobjective/test_nsga2.py
  nevergrad/optimization/recorded_recommendations.csv
  nevergrad/optimization/test_optimizerlib.py
Labels: CLA Signed

#1039 Remove useless code
  nevergrad/parametrization/core.py
  nevergrad/parametrization/data.py
Labels: CLA Signed

#1040 Move UnsupportedError to errors module
  nevergrad/common/errors.py
  nevergrad/parametrization/core.py
  nevergrad/parametrization/parameter.py
  nevergrad/parametrization/utils.py
Labels: CLA Signed

#1043 Externalize subparameter calls and simplify Parameter copy
  CHANGELOG.md
  nevergrad/functions/leaderboard.csv
  nevergrad/parametrization/choice.py
  nevergrad/parametrization/core.py
  nevergrad/parametrization/data.py
  nevergrad/parametrization/helpers.py
  nevergrad/parametrization/mutation.py
  nevergrad/parametrization/utils.py
Labels: CLA Signed, Difficulty: High, Priority: High

#1044 Group Parameter containers in container module
  CHANGELOG.md
  nevergrad/optimization/es.py
  nevergrad/parametrization/choice.py
  nevergrad/parametrization/container.py
  nevergrad/parametrization/core.py
  nevergrad/parametrization/data.py
  nevergrad/parametrization/helpers.py
  nevergrad/parametrization/parameter.py
Labels: CLA Signed, Difficulty: Low, Priority: High

#1012 Update EPS
  nevergrad/optimization/multiobjective/core.py
Labels: CLA Signed

#1049 Check links only on master
  .circleci/config.yml
  docs/conf.py
Labels: CLA Signed, Difficulty: Low, Priority: Medium

#1048 Simplify Parameter.copy()
  .circleci/config.yml
  CHANGELOG.md
  nevergrad/benchmark/xpbase.py
  nevergrad/functions/base.py
  nevergrad/functions/images/imagelosses.py
  nevergrad/optimization/es.py
  nevergrad/optimization/recorded_recommendations.csv
  nevergrad/parametrization/core.py
  nevergrad/parametrization/data.py
  nevergrad/parametrization/test_parameter.py
Labels: CLA Signed, Difficulty: Medium, Priority: High

#1045 Restructure Parameters around Layered class
  CHANGELOG.md
  nevergrad/common/errors.py
  nevergrad/parametrization/_layering.py
  nevergrad/parametrization/choice.py
  nevergrad/parametrization/container.py
  nevergrad/parametrization/core.py
  nevergrad/parametrization/data.py
  nevergrad/parametrization/test_parameter.py
Labels: CLA Signed, Difficulty: High, Priority: Critical

#1054 Add a simple early stopping mechanism
  CHANGELOG.md
  docs/optimizers_ref.rst
  docs/parametrization_ref.rst
  nevergrad/common/errors.py
  nevergrad/optimization/base.py
  nevergrad/optimization/callbacks.py
  nevergrad/optimization/test_callbacks.py
Labels: CLA Signed, Difficulty: Low, Priority: High

#1055 Adding photosic in benchmarks
  nevergrad/benchmark/experiments.py
  nevergrad/functions/photonics/core.py
Labels: CLA Signed

#1056 Prevent DE/PSO interactions in ParaPortfolio
  nevergrad/optimization/differentialevolution.py
  nevergrad/optimization/optimizerlib.py
  nevergrad/optimization/test_optimizerlib.py
Labels: CLA Signed, Difficulty: Low, Priority: Medium

#1058 Add MOO mode for 1+1 + fix DE uniform sampling
  CHANGELOG.md
  nevergrad/benchmark/test_xpbase.py
  nevergrad/functions/images/core.py
  nevergrad/optimization/base.py
  nevergrad/optimization/differentialevolution.py
  nevergrad/optimization/experimentalvariants.py
  nevergrad/optimization/multiobjective/core.py
  nevergrad/optimization/oneshot.py
  nevergrad/optimization/optimizerlib.py
  nevergrad/optimization/test_callbacks.py
  nevergrad/optimization/test_optimizerlib.py
Labels: CLA Signed, Difficulty: Low, Priority: High, Type: Enhancement

#1061 Keep 1+1 sigma unchanged if equal loss
  nevergrad/functions/pyomo/test_core.py
  nevergrad/optimization/optimizerlib.py
Labels: CLA Signed

#1053 Add a constraint layer
  nevergrad/ops/__init__.py
  nevergrad/ops/constraints.py
  nevergrad/ops/test_constraints.py
  nevergrad/optimization/base.py
  nevergrad/optimization/test_optimizerlib.py
  nevergrad/parametrization/_layering.py
  nevergrad/parametrization/container.py
  nevergrad/parametrization/core.py
  nevergrad/parametrization/data.py
  nevergrad/parametrization/utils.py
Labels: CLA Signed, Difficulty: Medium, Priority: Critical

#1062 Upgrade version to 0.4.3.post1
  nevergrad/__init__.py
  nevergrad/ops/test_constraints.py
Labels: CLA Signed
