Repository facebookresearch/nevergrad, pull requests merged in 2021-10, with the labels that each got.

#1247 Add MetaModelDiagonalCMA in xp variants
  nevergrad/optimization/experimentalvariants.py
  nevergrad/optimization/families.py
  nevergrad/optimization/optimizerlib.py
  nevergrad/optimization/recorded_recommendations.csv
Labels: CLA Signed, Status: Review needed

#1246 Activate more unit tests with env variable NEVERGRAD_SPECIAL_TESTS
  nevergrad/optimization/test_optimizerlib.py
  nevergrad/optimization/test_special.py
Labels: CLA Signed, Status: Review needed

#1255 Fix Gym stuff and skip Pymoo stuff
  nevergrad/functions/gym/multigym.py
  nevergrad/functions/gym/test_multigym.py
  nevergrad/optimization/recastlib.py
  nevergrad/optimization/test_optimizerlib.py
Labels: CLA Signed

#1018 Add a test for moo cv
  nevergrad/functions/test_base.py
Labels: Status: In Progess, CLA Signed

#1252 Fix issue where nevergrad sets log level internally
  nevergrad/optimization/callbacks.py
  nevergrad/optimization/multiobjective/nsga2.py
  nevergrad/optimization/optimizerlib.py
Labels: CLA Signed

#1260 Fix docs
  nevergrad/benchmark/gymexperiments.py
Labels: CLA Signed

#1264 Get rid of overflow
  nevergrad/functions/functionlib.py
Labels: CLA Signed
