Repository facebookresearch/nevergrad, pull requests merged in 2021-04, with the labels that each got.

#1090 Fix bad rst rendering
  docs/benchmarking.rst
Labels: CLA Signed

#1093 Release 0.4.3.post2
  nevergrad/__init__.py
Labels: CLA Signed

#997 Reducing yawidebbob.
  nevergrad/benchmark/experiments.py
Labels: CLA Signed

#1097 Fix MSR coefficients
  nevergrad/optimization/optimizerlib.py
  nevergrad/optimization/recorded_recommendations.csv
Labels: CLA Signed

#1098 Check attribute outside init in CI
  .circleci/config.yml
Labels: CLA Signed

#1099 Update index page to use NGOpt
  docs/index.rst
  nevergrad/optimization/test_doc.py
Labels: CLA Signed

#1100 Change 1+1 to NGOpt throughout the documentation
  docs/getting_started.rst
  docs/optimization.rst
  nevergrad/optimization/test_doc.py
  nevergrad/parametrization/test_param_doc.py
Labels: CLA Signed

#1096 Remove pointless print
  nevergrad/functions/rocket/rocket.py
Labels: CLA Signed

#1102 Refactor CMA wrapper
  nevergrad/__init__.py
  nevergrad/optimization/optimizerlib.py
  nevergrad/optimization/test_optimizerlib.py
Labels: CLA Signed, Difficulty: Low, Priority: Medium, Type: Refactoring

#1086 Refactor recombination/mutation to use layers (experimental)
  CHANGELOG.md
  nevergrad/__init__.py
  nevergrad/functions/arcoating/core.py
  nevergrad/functions/functionlib.py
  nevergrad/functions/images/core.py
  nevergrad/functions/photonics/core.py
  nevergrad/functions/photonics/test_core.py
  nevergrad/ops/__init__.py
  nevergrad/optimization/test_callbacks.py
  nevergrad/parametrization/_layering.py
  nevergrad/parametrization/container.py
  nevergrad/parametrization/core.py
  nevergrad/parametrization/data.py
  nevergrad/parametrization/mutation.py
  nevergrad/parametrization/test_mutation.py
Labels: CLA Signed, Difficulty: High, Priority: Medium

#1106 Better random state initialization
  CHANGELOG.md
  nevergrad/functions/ml/test_mlfunctionlib.py
  nevergrad/functions/pyomo/test_core.py
  nevergrad/optimization/utils.py
  nevergrad/parametrization/_layering.py
  nevergrad/parametrization/choice.py
  nevergrad/parametrization/container.py
  nevergrad/parametrization/core.py
  nevergrad/parametrization/test_parameter.py
Labels: CLA Signed

#1108 Remove progress bar in circleci install
  .circleci/config.yml
Labels: CLA Signed

#1109 Update mlda
  nevergrad/benchmark/experiments.py
  nevergrad/benchmark/test_xpbase.py
  nevergrad/functions/mlda/datasets.py
  nevergrad/functions/mlda/problems.py
  nevergrad/functions/mlda/test_problems.py
Labels: CLA Signed

#1111 Record number of objectives
  nevergrad/benchmark/test_xpbase.py
  nevergrad/benchmark/xpbase.py
Labels: CLA Signed
