Repository facebookresearch/nevergrad, pull requests merged in 2021-03, with the labels that each got.

#1050 Handle bounds through the layer system
  CHANGELOG.md
  nevergrad/common/errors.py
  nevergrad/common/test_tools.py
  nevergrad/common/tools.py
  nevergrad/functions/leaderboard.csv
  nevergrad/ops/constraints.py
  nevergrad/optimization/test_externalbo.py
  nevergrad/optimization/test_utils.py
  nevergrad/optimization/utils.py
  nevergrad/parametrization/_datalayers.py
  nevergrad/parametrization/_layering.py
  nevergrad/parametrization/core.py
  nevergrad/parametrization/data.py
  nevergrad/parametrization/helpers.py
  nevergrad/parametrization/test_layers.py
  nevergrad/parametrization/test_parameter.py
  nevergrad/parametrization/test_parameters_legacy.py
  nevergrad/parametrization/transforms.py
Labels: CLA Signed, Difficulty: High, Priority: High

#1065 Add a sampling layers to structure choice parameters
  CHANGELOG.md
  nevergrad/optimization/optimizerlib.py
  nevergrad/optimization/test_callbacks.py
  nevergrad/optimization/test_optimizerlib.py
  nevergrad/parametrization/_datalayers.py
  nevergrad/parametrization/_layering.py
  nevergrad/parametrization/choice.py
  nevergrad/parametrization/data.py
  nevergrad/parametrization/mutation.py
  nevergrad/parametrization/test_layers.py
  nevergrad/parametrization/test_mutation.py
  nevergrad/parametrization/test_parameter.py
  nevergrad/parametrization/test_parameters_legacy.py
  nevergrad/parametrization/test_utils.py
Labels: CLA Signed, Difficulty: High, Priority: Medium, Type: Breaking changes, Type: Enhancement

#1068 Externalize the deterministic behavior + Improve sampling optimizers
  CHANGELOG.md
  nevergrad/functions/test_base.py
  nevergrad/optimization/base.py
  nevergrad/optimization/differentialevolution.py
  nevergrad/optimization/experimentalvariants.py
  nevergrad/optimization/oneshot.py
  nevergrad/optimization/optimizerlib.py
  nevergrad/optimization/test_optimizerlib.py
  nevergrad/optimization/utils.py
  nevergrad/parametrization/_datalayers.py
  nevergrad/parametrization/_layering.py
  nevergrad/parametrization/choice.py
  nevergrad/parametrization/container.py
  nevergrad/parametrization/core.py
  nevergrad/parametrization/data.py
  nevergrad/parametrization/helpers.py
  nevergrad/parametrization/parameter.py
  nevergrad/parametrization/test_layers.py
  nevergrad/parametrization/test_parameter.py
  nevergrad/parametrization/test_parameters_legacy.py
Labels: CLA Signed

#1069 Improve early stopping callback documentation
  nevergrad/optimization/callbacks.py
  nevergrad/optimization/test_callbacks.py
Labels: CLA Signed

#1070 Improve BO initial sampling
  nevergrad/optimization/optimizerlib.py
Labels: CLA Signed

#1072 Clarify suggest arguments
  docs/optimization.rst
Labels: Difficulty: Low, Priority: Low

#1075 Skip rocket xp test for speed
  nevergrad/benchmark/experiments.py
  nevergrad/functions/rocket/__init__.py
  nevergrad/functions/rocket/core.py
  nevergrad/functions/rocket/rocket.py
  nevergrad/functions/rocket/test_rocket.py
Labels: CLA Signed, Difficulty: Low, Priority: High

#1074 Update parametrization flatten function
  nevergrad/optimization/callbacks.py
  nevergrad/optimization/optimizerlib.py
  nevergrad/optimization/test_callbacks.py
  nevergrad/optimization/test_utils.py
  nevergrad/optimization/utils.py
  nevergrad/parametrization/helpers.py
  nevergrad/parametrization/test_utils.py
Labels: CLA Signed, Difficulty: Medium, Priority: High, Type: Breaking changes, Type: Enhancement

#1073 Add configuration for PSO + simplifications
  CHANGELOG.md
  nevergrad/optimization/experimentalvariants.py
  nevergrad/optimization/optimizerlib.py
  nevergrad/optimization/recorded_recommendations.csv
Labels: CLA Signed, Difficulty: Low, Priority: Medium, Type: Breaking changes, Type: Enhancement

#1041 Remove deprecated stuff
  nevergrad/benchmark/experiments.py
  nevergrad/functions/images/__init__.py
  nevergrad/functions/images/test_core.py
Labels: CLA Signed

#1042 Morphing with Nevergrad
  nevergrad/benchmark/experiments.py
  nevergrad/functions/images/core.py
  setup.py
Labels: CLA Signed

#1004 Add MOO xp variants
  nevergrad/benchmark/experiments.py
Labels: CLA Signed

#803 Add a specific ArrayExperimentFunction using symmetry for diversity
  nevergrad/benchmark/experiments.py
  nevergrad/functions/base.py
  nevergrad/functions/rocket/rocket.py
  nevergrad/functions/test_base.py
Labels: CLA Signed

#999 MOO can be done by multiple single optim methods.
  nevergrad/benchmark/xpbase.py
  nevergrad/functions/arcoating/core.py
  nevergrad/functions/base.py
  nevergrad/functions/control/core.py
  nevergrad/functions/functionlib.py
  nevergrad/functions/games/game.py
  nevergrad/functions/helpers.py
  nevergrad/functions/images/core.py
  nevergrad/functions/ml/mlfunctionlib.py
  nevergrad/functions/photonics/core.py
  nevergrad/functions/rl/agents.py
  nevergrad/optimization/differentialevolution.py
  nevergrad/optimization/experimentalvariants.py
  nevergrad/optimization/optimizerlib.py
  nevergrad/optimization/recorded_recommendations.csv
Labels: CLA Signed

#1079 [PR on PR] Fix constraints
  nevergrad/optimization/base.py
  nevergrad/optimization/test_optimizerlib.py
Labels: CLA Signed

#1047 Dedicate half constraint budget to a suboptimizer
  CHANGELOG.md
  nevergrad/optimization/base.py
  nevergrad/optimization/test_optimizerlib.py
  nevergrad/parametrization/core.py
Labels: CLA Signed

#1078 Add an angle layer
  nevergrad/parametrization/_datalayers.py
  nevergrad/parametrization/_layering.py
  nevergrad/parametrization/container.py
  nevergrad/parametrization/core.py
  nevergrad/parametrization/data.py
  nevergrad/parametrization/parameter.py
  nevergrad/parametrization/test_layers.py
  nevergrad/parametrization/test_parameter.py
Labels: CLA Signed, Difficulty: Medium, Priority: Medium

#1083 Move back PortfolioDiscreteOnePlusOne to optlib since mentioned in doc
  nevergrad/optimization/experimentalvariants.py
  nevergrad/optimization/optimizerlib.py
  nevergrad/optimization/test_optimizerlib.py
Labels: CLA Signed

#1077 Add lower and upper arguments to Array
  CHANGELOG.md
  nevergrad/optimization/test_optimizerlib.py
  nevergrad/parametrization/_datalayers.py
  nevergrad/parametrization/data.py
  nevergrad/parametrization/test_parameter.py
  nevergrad/parametrization/test_parameters_legacy.py
Labels: CLA Signed, Difficulty: Low, Priority: Low, Type: Enhancement

#1085 Lotka-Volterra equations.
  nevergrad/functions/fishing/__init__.py
  nevergrad/functions/fishing/core.py
  nevergrad/functions/fishing/test_core.py
Labels: CLA Signed
